#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HXOA")]
	public partial class HXOADBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertFunction_Setting(Function_Setting instance);
    partial void UpdateFunction_Setting(Function_Setting instance);
    partial void DeleteFunction_Setting(Function_Setting instance);
    partial void InsertRole_Right(Role_Right instance);
    partial void UpdateRole_Right(Role_Right instance);
    partial void DeleteRole_Right(Role_Right instance);
    partial void InsertRoles(Roles instance);
    partial void UpdateRoles(Roles instance);
    partial void DeleteRoles(Roles instance);
    partial void InsertUsers(Users instance);
    partial void UpdateUsers(Users instance);
    partial void DeleteUsers(Users instance);
    partial void InsertUsers_Roles(Users_Roles instance);
    partial void UpdateUsers_Roles(Users_Roles instance);
    partial void DeleteUsers_Roles(Users_Roles instance);
    #endregion
		
		public HXOADBDataContext() : 
				base(global::DB.Properties.Settings.Default.HXOAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HXOADBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HXOADBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HXOADBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HXOADBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Function_Setting> Function_Setting
		{
			get
			{
				return this.GetTable<Function_Setting>();
			}
		}
		
		public System.Data.Linq.Table<Role_Right> Role_Right
		{
			get
			{
				return this.GetTable<Role_Right>();
			}
		}
		
		public System.Data.Linq.Table<Roles> Roles
		{
			get
			{
				return this.GetTable<Roles>();
			}
		}
		
		public System.Data.Linq.Table<Users> Users
		{
			get
			{
				return this.GetTable<Users>();
			}
		}
		
		public System.Data.Linq.Table<Users_Roles> Users_Roles
		{
			get
			{
				return this.GetTable<Users_Roles>();
			}
		}
		
		public System.Data.Linq.Table<V_material_deliver_report> V_material_deliver_report
		{
			get
			{
				return this.GetTable<V_material_deliver_report>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Function_Setting")]
	public partial class Function_Setting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _fs_num;
		
		private string _fs_funcno;
		
		private string _fs_model;
		
		private string _fs_imageurl;
		
		private string _fs_funcname;
		
		private string _fs_menuurl;
		
		private System.Nullable<int> _fs_active;
		
		private System.Nullable<int> _fs_export;
		
		private System.Nullable<int> _fs_view;
		
		private System.Nullable<int> _fs_insert;
		
		private System.Nullable<int> _fs_update;
		
		private System.Nullable<int> _fs_delete;
		
		private System.Nullable<int> _fs_status;
		
		private System.Nullable<int> _fs_flag;
		
		private System.Nullable<int> _fs_id;
		
		private System.Nullable<int> _fs_pid;
		
		private System.Data.Linq.Binary _lastmodify;
		
		private int _Sort;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfs_numChanging(long value);
    partial void Onfs_numChanged();
    partial void Onfs_funcnoChanging(string value);
    partial void Onfs_funcnoChanged();
    partial void Onfs_modelChanging(string value);
    partial void Onfs_modelChanged();
    partial void Onfs_imageurlChanging(string value);
    partial void Onfs_imageurlChanged();
    partial void Onfs_funcnameChanging(string value);
    partial void Onfs_funcnameChanged();
    partial void Onfs_menuurlChanging(string value);
    partial void Onfs_menuurlChanged();
    partial void Onfs_activeChanging(System.Nullable<int> value);
    partial void Onfs_activeChanged();
    partial void Onfs_exportChanging(System.Nullable<int> value);
    partial void Onfs_exportChanged();
    partial void Onfs_viewChanging(System.Nullable<int> value);
    partial void Onfs_viewChanged();
    partial void Onfs_insertChanging(System.Nullable<int> value);
    partial void Onfs_insertChanged();
    partial void Onfs_updateChanging(System.Nullable<int> value);
    partial void Onfs_updateChanged();
    partial void Onfs_deleteChanging(System.Nullable<int> value);
    partial void Onfs_deleteChanged();
    partial void Onfs_statusChanging(System.Nullable<int> value);
    partial void Onfs_statusChanged();
    partial void Onfs_flagChanging(System.Nullable<int> value);
    partial void Onfs_flagChanged();
    partial void Onfs_idChanging(System.Nullable<int> value);
    partial void Onfs_idChanged();
    partial void Onfs_pidChanging(System.Nullable<int> value);
    partial void Onfs_pidChanged();
    partial void OnlastmodifyChanging(System.Data.Linq.Binary value);
    partial void OnlastmodifyChanged();
    partial void OnSortChanging(int value);
    partial void OnSortChanged();
    #endregion
		
		public Function_Setting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_num", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long fs_num
		{
			get
			{
				return this._fs_num;
			}
			set
			{
				if ((this._fs_num != value))
				{
					this.Onfs_numChanging(value);
					this.SendPropertyChanging();
					this._fs_num = value;
					this.SendPropertyChanged("fs_num");
					this.Onfs_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_funcno", DbType="VarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string fs_funcno
		{
			get
			{
				return this._fs_funcno;
			}
			set
			{
				if ((this._fs_funcno != value))
				{
					this.Onfs_funcnoChanging(value);
					this.SendPropertyChanging();
					this._fs_funcno = value;
					this.SendPropertyChanged("fs_funcno");
					this.Onfs_funcnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_model", DbType="VarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string fs_model
		{
			get
			{
				return this._fs_model;
			}
			set
			{
				if ((this._fs_model != value))
				{
					this.Onfs_modelChanging(value);
					this.SendPropertyChanging();
					this._fs_model = value;
					this.SendPropertyChanged("fs_model");
					this.Onfs_modelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_imageurl", DbType="VarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string fs_imageurl
		{
			get
			{
				return this._fs_imageurl;
			}
			set
			{
				if ((this._fs_imageurl != value))
				{
					this.Onfs_imageurlChanging(value);
					this.SendPropertyChanging();
					this._fs_imageurl = value;
					this.SendPropertyChanged("fs_imageurl");
					this.Onfs_imageurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_funcname", DbType="VarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string fs_funcname
		{
			get
			{
				return this._fs_funcname;
			}
			set
			{
				if ((this._fs_funcname != value))
				{
					this.Onfs_funcnameChanging(value);
					this.SendPropertyChanging();
					this._fs_funcname = value;
					this.SendPropertyChanged("fs_funcname");
					this.Onfs_funcnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_menuurl", DbType="VarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string fs_menuurl
		{
			get
			{
				return this._fs_menuurl;
			}
			set
			{
				if ((this._fs_menuurl != value))
				{
					this.Onfs_menuurlChanging(value);
					this.SendPropertyChanging();
					this._fs_menuurl = value;
					this.SendPropertyChanged("fs_menuurl");
					this.Onfs_menuurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_active", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> fs_active
		{
			get
			{
				return this._fs_active;
			}
			set
			{
				if ((this._fs_active != value))
				{
					this.Onfs_activeChanging(value);
					this.SendPropertyChanging();
					this._fs_active = value;
					this.SendPropertyChanged("fs_active");
					this.Onfs_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_export", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> fs_export
		{
			get
			{
				return this._fs_export;
			}
			set
			{
				if ((this._fs_export != value))
				{
					this.Onfs_exportChanging(value);
					this.SendPropertyChanging();
					this._fs_export = value;
					this.SendPropertyChanged("fs_export");
					this.Onfs_exportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_view", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> fs_view
		{
			get
			{
				return this._fs_view;
			}
			set
			{
				if ((this._fs_view != value))
				{
					this.Onfs_viewChanging(value);
					this.SendPropertyChanging();
					this._fs_view = value;
					this.SendPropertyChanged("fs_view");
					this.Onfs_viewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_insert", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> fs_insert
		{
			get
			{
				return this._fs_insert;
			}
			set
			{
				if ((this._fs_insert != value))
				{
					this.Onfs_insertChanging(value);
					this.SendPropertyChanging();
					this._fs_insert = value;
					this.SendPropertyChanged("fs_insert");
					this.Onfs_insertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_update", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> fs_update
		{
			get
			{
				return this._fs_update;
			}
			set
			{
				if ((this._fs_update != value))
				{
					this.Onfs_updateChanging(value);
					this.SendPropertyChanging();
					this._fs_update = value;
					this.SendPropertyChanged("fs_update");
					this.Onfs_updateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_delete", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> fs_delete
		{
			get
			{
				return this._fs_delete;
			}
			set
			{
				if ((this._fs_delete != value))
				{
					this.Onfs_deleteChanging(value);
					this.SendPropertyChanging();
					this._fs_delete = value;
					this.SendPropertyChanged("fs_delete");
					this.Onfs_deleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_status", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> fs_status
		{
			get
			{
				return this._fs_status;
			}
			set
			{
				if ((this._fs_status != value))
				{
					this.Onfs_statusChanging(value);
					this.SendPropertyChanging();
					this._fs_status = value;
					this.SendPropertyChanged("fs_status");
					this.Onfs_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_flag", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> fs_flag
		{
			get
			{
				return this._fs_flag;
			}
			set
			{
				if ((this._fs_flag != value))
				{
					this.Onfs_flagChanging(value);
					this.SendPropertyChanging();
					this._fs_flag = value;
					this.SendPropertyChanged("fs_flag");
					this.Onfs_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_id", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> fs_id
		{
			get
			{
				return this._fs_id;
			}
			set
			{
				if ((this._fs_id != value))
				{
					this.Onfs_idChanging(value);
					this.SendPropertyChanging();
					this._fs_id = value;
					this.SendPropertyChanged("fs_id");
					this.Onfs_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fs_pid", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> fs_pid
		{
			get
			{
				return this._fs_pid;
			}
			set
			{
				if ((this._fs_pid != value))
				{
					this.Onfs_pidChanging(value);
					this.SendPropertyChanging();
					this._fs_pid = value;
					this.SendPropertyChanged("fs_pid");
					this.Onfs_pidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodify", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary lastmodify
		{
			get
			{
				return this._lastmodify;
			}
			set
			{
				if ((this._lastmodify != value))
				{
					this.OnlastmodifyChanging(value);
					this.SendPropertyChanging();
					this._lastmodify = value;
					this.SendPropertyChanged("lastmodify");
					this.OnlastmodifyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this.OnSortChanging(value);
					this.SendPropertyChanging();
					this._Sort = value;
					this.SendPropertyChanged("Sort");
					this.OnSortChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Role_Right")]
	public partial class Role_Right : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ur_num;
		
		private int _ur_rolesid;
		
		private string _ur_funcno;
		
		private string _ur_model;
		
		private string _ur_imageurl;
		
		private string _ur_funcname;
		
		private string _ur_menuurl;
		
		private System.Nullable<int> _ur_active;
		
		private System.Nullable<int> _ur_export;
		
		private System.Nullable<int> _ur_view;
		
		private System.Nullable<int> _ur_insert;
		
		private System.Nullable<int> _ur_update;
		
		private System.Nullable<int> _ur_delete;
		
		private System.Nullable<int> _ur_status;
		
		private System.Nullable<int> _ur_flag;
		
		private System.Nullable<int> _ur_id;
		
		private System.Nullable<int> _ur_pid;
		
		private System.Data.Linq.Binary _lastmodify;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onur_numChanging(long value);
    partial void Onur_numChanged();
    partial void Onur_rolesidChanging(int value);
    partial void Onur_rolesidChanged();
    partial void Onur_funcnoChanging(string value);
    partial void Onur_funcnoChanged();
    partial void Onur_modelChanging(string value);
    partial void Onur_modelChanged();
    partial void Onur_imageurlChanging(string value);
    partial void Onur_imageurlChanged();
    partial void Onur_funcnameChanging(string value);
    partial void Onur_funcnameChanged();
    partial void Onur_menuurlChanging(string value);
    partial void Onur_menuurlChanged();
    partial void Onur_activeChanging(System.Nullable<int> value);
    partial void Onur_activeChanged();
    partial void Onur_exportChanging(System.Nullable<int> value);
    partial void Onur_exportChanged();
    partial void Onur_viewChanging(System.Nullable<int> value);
    partial void Onur_viewChanged();
    partial void Onur_insertChanging(System.Nullable<int> value);
    partial void Onur_insertChanged();
    partial void Onur_updateChanging(System.Nullable<int> value);
    partial void Onur_updateChanged();
    partial void Onur_deleteChanging(System.Nullable<int> value);
    partial void Onur_deleteChanged();
    partial void Onur_statusChanging(System.Nullable<int> value);
    partial void Onur_statusChanged();
    partial void Onur_flagChanging(System.Nullable<int> value);
    partial void Onur_flagChanged();
    partial void Onur_idChanging(System.Nullable<int> value);
    partial void Onur_idChanged();
    partial void Onur_pidChanging(System.Nullable<int> value);
    partial void Onur_pidChanged();
    partial void OnlastmodifyChanging(System.Data.Linq.Binary value);
    partial void OnlastmodifyChanged();
    #endregion
		
		public Role_Right()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_num", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public long ur_num
		{
			get
			{
				return this._ur_num;
			}
			set
			{
				if ((this._ur_num != value))
				{
					this.Onur_numChanging(value);
					this.SendPropertyChanging();
					this._ur_num = value;
					this.SendPropertyChanged("ur_num");
					this.Onur_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_rolesid", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int ur_rolesid
		{
			get
			{
				return this._ur_rolesid;
			}
			set
			{
				if ((this._ur_rolesid != value))
				{
					this.Onur_rolesidChanging(value);
					this.SendPropertyChanging();
					this._ur_rolesid = value;
					this.SendPropertyChanged("ur_rolesid");
					this.Onur_rolesidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_funcno", DbType="VarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ur_funcno
		{
			get
			{
				return this._ur_funcno;
			}
			set
			{
				if ((this._ur_funcno != value))
				{
					this.Onur_funcnoChanging(value);
					this.SendPropertyChanging();
					this._ur_funcno = value;
					this.SendPropertyChanged("ur_funcno");
					this.Onur_funcnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_model", DbType="VarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ur_model
		{
			get
			{
				return this._ur_model;
			}
			set
			{
				if ((this._ur_model != value))
				{
					this.Onur_modelChanging(value);
					this.SendPropertyChanging();
					this._ur_model = value;
					this.SendPropertyChanged("ur_model");
					this.Onur_modelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_imageurl", DbType="VarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string ur_imageurl
		{
			get
			{
				return this._ur_imageurl;
			}
			set
			{
				if ((this._ur_imageurl != value))
				{
					this.Onur_imageurlChanging(value);
					this.SendPropertyChanging();
					this._ur_imageurl = value;
					this.SendPropertyChanged("ur_imageurl");
					this.Onur_imageurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_funcname", DbType="VarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string ur_funcname
		{
			get
			{
				return this._ur_funcname;
			}
			set
			{
				if ((this._ur_funcname != value))
				{
					this.Onur_funcnameChanging(value);
					this.SendPropertyChanging();
					this._ur_funcname = value;
					this.SendPropertyChanged("ur_funcname");
					this.Onur_funcnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_menuurl", DbType="VarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string ur_menuurl
		{
			get
			{
				return this._ur_menuurl;
			}
			set
			{
				if ((this._ur_menuurl != value))
				{
					this.Onur_menuurlChanging(value);
					this.SendPropertyChanging();
					this._ur_menuurl = value;
					this.SendPropertyChanged("ur_menuurl");
					this.Onur_menuurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_active", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ur_active
		{
			get
			{
				return this._ur_active;
			}
			set
			{
				if ((this._ur_active != value))
				{
					this.Onur_activeChanging(value);
					this.SendPropertyChanging();
					this._ur_active = value;
					this.SendPropertyChanged("ur_active");
					this.Onur_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_export", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ur_export
		{
			get
			{
				return this._ur_export;
			}
			set
			{
				if ((this._ur_export != value))
				{
					this.Onur_exportChanging(value);
					this.SendPropertyChanging();
					this._ur_export = value;
					this.SendPropertyChanged("ur_export");
					this.Onur_exportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_view", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ur_view
		{
			get
			{
				return this._ur_view;
			}
			set
			{
				if ((this._ur_view != value))
				{
					this.Onur_viewChanging(value);
					this.SendPropertyChanging();
					this._ur_view = value;
					this.SendPropertyChanged("ur_view");
					this.Onur_viewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_insert", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ur_insert
		{
			get
			{
				return this._ur_insert;
			}
			set
			{
				if ((this._ur_insert != value))
				{
					this.Onur_insertChanging(value);
					this.SendPropertyChanging();
					this._ur_insert = value;
					this.SendPropertyChanged("ur_insert");
					this.Onur_insertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_update", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ur_update
		{
			get
			{
				return this._ur_update;
			}
			set
			{
				if ((this._ur_update != value))
				{
					this.Onur_updateChanging(value);
					this.SendPropertyChanging();
					this._ur_update = value;
					this.SendPropertyChanged("ur_update");
					this.Onur_updateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_delete", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ur_delete
		{
			get
			{
				return this._ur_delete;
			}
			set
			{
				if ((this._ur_delete != value))
				{
					this.Onur_deleteChanging(value);
					this.SendPropertyChanging();
					this._ur_delete = value;
					this.SendPropertyChanged("ur_delete");
					this.Onur_deleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_status", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ur_status
		{
			get
			{
				return this._ur_status;
			}
			set
			{
				if ((this._ur_status != value))
				{
					this.Onur_statusChanging(value);
					this.SendPropertyChanging();
					this._ur_status = value;
					this.SendPropertyChanged("ur_status");
					this.Onur_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_flag", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ur_flag
		{
			get
			{
				return this._ur_flag;
			}
			set
			{
				if ((this._ur_flag != value))
				{
					this.Onur_flagChanging(value);
					this.SendPropertyChanging();
					this._ur_flag = value;
					this.SendPropertyChanged("ur_flag");
					this.Onur_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_id", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ur_id
		{
			get
			{
				return this._ur_id;
			}
			set
			{
				if ((this._ur_id != value))
				{
					this.Onur_idChanging(value);
					this.SendPropertyChanging();
					this._ur_id = value;
					this.SendPropertyChanged("ur_id");
					this.Onur_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_pid", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ur_pid
		{
			get
			{
				return this._ur_pid;
			}
			set
			{
				if ((this._ur_pid != value))
				{
					this.Onur_pidChanging(value);
					this.SendPropertyChanging();
					this._ur_pid = value;
					this.SendPropertyChanged("ur_pid");
					this.Onur_pidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodify", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary lastmodify
		{
			get
			{
				return this._lastmodify;
			}
			set
			{
				if ((this._lastmodify != value))
				{
					this.OnlastmodifyChanging(value);
					this.SendPropertyChanging();
					this._lastmodify = value;
					this.SendPropertyChanged("lastmodify");
					this.OnlastmodifyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roles")]
	public partial class Roles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RolesId;
		
		private string _RolesName;
		
		private string _RoleType;
		
		private System.Nullable<int> _Status;
		
		private string _Flag;
		
		private System.Data.Linq.Binary _LastModify;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRolesIdChanging(int value);
    partial void OnRolesIdChanged();
    partial void OnRolesNameChanging(string value);
    partial void OnRolesNameChanged();
    partial void OnRoleTypeChanging(string value);
    partial void OnRoleTypeChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnFlagChanging(string value);
    partial void OnFlagChanged();
    partial void OnLastModifyChanging(System.Data.Linq.Binary value);
    partial void OnLastModifyChanged();
    #endregion
		
		public Roles()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RolesId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int RolesId
		{
			get
			{
				return this._RolesId;
			}
			set
			{
				if ((this._RolesId != value))
				{
					this.OnRolesIdChanging(value);
					this.SendPropertyChanging();
					this._RolesId = value;
					this.SendPropertyChanged("RolesId");
					this.OnRolesIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RolesName", DbType="VarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string RolesName
		{
			get
			{
				return this._RolesName;
			}
			set
			{
				if ((this._RolesName != value))
				{
					this.OnRolesNameChanging(value);
					this.SendPropertyChanging();
					this._RolesName = value;
					this.SendPropertyChanged("RolesName");
					this.OnRolesNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleType", DbType="VarChar(4)", UpdateCheck=UpdateCheck.Never)]
		public string RoleType
		{
			get
			{
				return this._RoleType;
			}
			set
			{
				if ((this._RoleType != value))
				{
					this.OnRoleTypeChanging(value);
					this.SendPropertyChanging();
					this._RoleType = value;
					this.SendPropertyChanged("RoleType");
					this.OnRoleTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="VarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModify", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary LastModify
		{
			get
			{
				return this._LastModify;
			}
			set
			{
				if ((this._LastModify != value))
				{
					this.OnLastModifyChanging(value);
					this.SendPropertyChanging();
					this._LastModify = value;
					this.SendPropertyChanged("LastModify");
					this.OnLastModifyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _UserId;
		
		private string _UserId2;
		
		private System.Nullable<int> _UserNo;
		
		private string _UserName;
		
		private string _Password;
		
		private System.Nullable<int> _PrivId;
		
		private string _PrivId2;
		
		private string _PostPriv;
		
		private string _PostDept;
		
		private System.Nullable<int> _DeptId;
		
		private string _DeptId2;
		
		private System.Nullable<int> _CanBroadcast;
		
		private System.Nullable<int> _Sex;
		
		private System.Nullable<System.DateTime> _Birthday;
		
		private System.Nullable<int> _IsHideBirthday;
		
		private string _TelNoDept;
		
		private string _FaxNoDept;
		
		private string _AddressHome;
		
		private string _ZipHome;
		
		private string _TelHome;
		
		private string _Mobile;
		
		private System.Nullable<int> _IsHideMobile;
		
		private string _Bp;
		
		private string _Email;
		
		private string _Oicq;
		
		private string _Icq;
		
		private string _Msn;
		
		private string _Skype;
		
		private System.Data.Linq.Binary _Photo;
		
		private string _NickName;
		
		private System.Nullable<int> _Avatar;
		
		private System.Nullable<int> _MenuType;
		
		private System.Nullable<int> _MenuHide;
		
		private System.Nullable<int> _SmsOn;
		
		private System.Nullable<int> _CallSound;
		
		private System.Nullable<int> _Theme;
		
		private string _Note;
		
		private string _MytableLeft;
		
		private string _MytableRight;
		
		private System.Nullable<int> _EmailCapacity;
		
		private System.Nullable<int> _FolderCapacity;
		
		private System.Nullable<float> _OnlineTime;
		
		private System.Nullable<int> _DutyType;
		
		private string _AttendCard;
		
		private System.Nullable<int> _State;
		
		private System.DateTime _LastPassTime;
		
		private System.DateTime _LastVisitTime;
		
		private string _LastIp;
		
		private System.Nullable<int> _Disabled;
		
		private string _BindIp;
		
		private System.Nullable<int> _UsingKey;
		
		private string _UGuid;
		
		private string _UKey;
		
		private string _UExt;
		
		private System.Nullable<int> _NotUser;
		
		private System.Nullable<int> _NotTable;
		
		private string _DefaultMenu;
		
		private string _TablePhoto;
		
		private System.Nullable<int> _WebmailNum;
		
		private System.Nullable<int> _WebmailCapacity;
		
		private string _AdUserId;
		
		private System.Nullable<int> _UsingAd;
		
		private System.Data.Linq.Binary _LastModify;
		
		private System.Nullable<int> _UserPosId;
		
		private string _userrole;
		
		private string _SOBJID;
		
		private System.Nullable<char> _STAT2;
		
		private System.Nullable<char> _ISTAT;
		
		private string _KOSTL;
		
		private string _BUKRS;
		
		private string _WERKS;
		
		private System.Nullable<char> _PERSG;
		
		private string _PERSK;
		
		private string _VDSK1;
		
		private string _GSBER;
		
		private string _BTRTL;
		
		private string _ABKRS;
		
		private string _STELL;
		
		private string _SBMOD;
		
		private string _ICNUM;
		
		private string _USERCARD;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnUserId2Changing(string value);
    partial void OnUserId2Changed();
    partial void OnUserNoChanging(System.Nullable<int> value);
    partial void OnUserNoChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPrivIdChanging(System.Nullable<int> value);
    partial void OnPrivIdChanged();
    partial void OnPrivId2Changing(string value);
    partial void OnPrivId2Changed();
    partial void OnPostPrivChanging(string value);
    partial void OnPostPrivChanged();
    partial void OnPostDeptChanging(string value);
    partial void OnPostDeptChanged();
    partial void OnDeptIdChanging(System.Nullable<int> value);
    partial void OnDeptIdChanged();
    partial void OnDeptId2Changing(string value);
    partial void OnDeptId2Changed();
    partial void OnCanBroadcastChanging(System.Nullable<int> value);
    partial void OnCanBroadcastChanged();
    partial void OnSexChanging(System.Nullable<int> value);
    partial void OnSexChanged();
    partial void OnBirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthdayChanged();
    partial void OnIsHideBirthdayChanging(System.Nullable<int> value);
    partial void OnIsHideBirthdayChanged();
    partial void OnTelNoDeptChanging(string value);
    partial void OnTelNoDeptChanged();
    partial void OnFaxNoDeptChanging(string value);
    partial void OnFaxNoDeptChanged();
    partial void OnAddressHomeChanging(string value);
    partial void OnAddressHomeChanged();
    partial void OnZipHomeChanging(string value);
    partial void OnZipHomeChanged();
    partial void OnTelHomeChanging(string value);
    partial void OnTelHomeChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnIsHideMobileChanging(System.Nullable<int> value);
    partial void OnIsHideMobileChanged();
    partial void OnBpChanging(string value);
    partial void OnBpChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnOicqChanging(string value);
    partial void OnOicqChanged();
    partial void OnIcqChanging(string value);
    partial void OnIcqChanged();
    partial void OnMsnChanging(string value);
    partial void OnMsnChanged();
    partial void OnSkypeChanging(string value);
    partial void OnSkypeChanged();
    partial void OnPhotoChanging(System.Data.Linq.Binary value);
    partial void OnPhotoChanged();
    partial void OnNickNameChanging(string value);
    partial void OnNickNameChanged();
    partial void OnAvatarChanging(System.Nullable<int> value);
    partial void OnAvatarChanged();
    partial void OnMenuTypeChanging(System.Nullable<int> value);
    partial void OnMenuTypeChanged();
    partial void OnMenuHideChanging(System.Nullable<int> value);
    partial void OnMenuHideChanged();
    partial void OnSmsOnChanging(System.Nullable<int> value);
    partial void OnSmsOnChanged();
    partial void OnCallSoundChanging(System.Nullable<int> value);
    partial void OnCallSoundChanged();
    partial void OnThemeChanging(System.Nullable<int> value);
    partial void OnThemeChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnMytableLeftChanging(string value);
    partial void OnMytableLeftChanged();
    partial void OnMytableRightChanging(string value);
    partial void OnMytableRightChanged();
    partial void OnEmailCapacityChanging(System.Nullable<int> value);
    partial void OnEmailCapacityChanged();
    partial void OnFolderCapacityChanging(System.Nullable<int> value);
    partial void OnFolderCapacityChanged();
    partial void OnOnlineTimeChanging(System.Nullable<float> value);
    partial void OnOnlineTimeChanged();
    partial void OnDutyTypeChanging(System.Nullable<int> value);
    partial void OnDutyTypeChanged();
    partial void OnAttendCardChanging(string value);
    partial void OnAttendCardChanged();
    partial void OnStateChanging(System.Nullable<int> value);
    partial void OnStateChanged();
    partial void OnLastPassTimeChanging(System.DateTime value);
    partial void OnLastPassTimeChanged();
    partial void OnLastVisitTimeChanging(System.DateTime value);
    partial void OnLastVisitTimeChanged();
    partial void OnLastIpChanging(string value);
    partial void OnLastIpChanged();
    partial void OnDisabledChanging(System.Nullable<int> value);
    partial void OnDisabledChanged();
    partial void OnBindIpChanging(string value);
    partial void OnBindIpChanged();
    partial void OnUsingKeyChanging(System.Nullable<int> value);
    partial void OnUsingKeyChanged();
    partial void OnUGuidChanging(string value);
    partial void OnUGuidChanged();
    partial void OnUKeyChanging(string value);
    partial void OnUKeyChanged();
    partial void OnUExtChanging(string value);
    partial void OnUExtChanged();
    partial void OnNotUserChanging(System.Nullable<int> value);
    partial void OnNotUserChanged();
    partial void OnNotTableChanging(System.Nullable<int> value);
    partial void OnNotTableChanged();
    partial void OnDefaultMenuChanging(string value);
    partial void OnDefaultMenuChanged();
    partial void OnTablePhotoChanging(string value);
    partial void OnTablePhotoChanged();
    partial void OnWebmailNumChanging(System.Nullable<int> value);
    partial void OnWebmailNumChanged();
    partial void OnWebmailCapacityChanging(System.Nullable<int> value);
    partial void OnWebmailCapacityChanged();
    partial void OnAdUserIdChanging(string value);
    partial void OnAdUserIdChanged();
    partial void OnUsingAdChanging(System.Nullable<int> value);
    partial void OnUsingAdChanged();
    partial void OnLastModifyChanging(System.Data.Linq.Binary value);
    partial void OnLastModifyChanged();
    partial void OnUserPosIdChanging(System.Nullable<int> value);
    partial void OnUserPosIdChanged();
    partial void OnuserroleChanging(string value);
    partial void OnuserroleChanged();
    partial void OnSOBJIDChanging(string value);
    partial void OnSOBJIDChanged();
    partial void OnSTAT2Changing(System.Nullable<char> value);
    partial void OnSTAT2Changed();
    partial void OnISTATChanging(System.Nullable<char> value);
    partial void OnISTATChanged();
    partial void OnKOSTLChanging(string value);
    partial void OnKOSTLChanged();
    partial void OnBUKRSChanging(string value);
    partial void OnBUKRSChanged();
    partial void OnWERKSChanging(string value);
    partial void OnWERKSChanged();
    partial void OnPERSGChanging(System.Nullable<char> value);
    partial void OnPERSGChanged();
    partial void OnPERSKChanging(string value);
    partial void OnPERSKChanged();
    partial void OnVDSK1Changing(string value);
    partial void OnVDSK1Changed();
    partial void OnGSBERChanging(string value);
    partial void OnGSBERChanged();
    partial void OnBTRTLChanging(string value);
    partial void OnBTRTLChanged();
    partial void OnABKRSChanging(string value);
    partial void OnABKRSChanged();
    partial void OnSTELLChanging(string value);
    partial void OnSTELLChanged();
    partial void OnSBMODChanging(string value);
    partial void OnSBMODChanged();
    partial void OnICNUMChanging(string value);
    partial void OnICNUMChanged();
    partial void OnUSERCARDChanging(string value);
    partial void OnUSERCARDChanged();
    #endregion
		
		public Users()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId2", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string UserId2
		{
			get
			{
				return this._UserId2;
			}
			set
			{
				if ((this._UserId2 != value))
				{
					this.OnUserId2Changing(value);
					this.SendPropertyChanging();
					this._UserId2 = value;
					this.SendPropertyChanged("UserId2");
					this.OnUserId2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNo", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> UserNo
		{
			get
			{
				return this._UserNo;
			}
			set
			{
				if ((this._UserNo != value))
				{
					this.OnUserNoChanging(value);
					this.SendPropertyChanging();
					this._UserNo = value;
					this.SendPropertyChanged("UserNo");
					this.OnUserNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrivId", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> PrivId
		{
			get
			{
				return this._PrivId;
			}
			set
			{
				if ((this._PrivId != value))
				{
					this.OnPrivIdChanging(value);
					this.SendPropertyChanging();
					this._PrivId = value;
					this.SendPropertyChanged("PrivId");
					this.OnPrivIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrivId2", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string PrivId2
		{
			get
			{
				return this._PrivId2;
			}
			set
			{
				if ((this._PrivId2 != value))
				{
					this.OnPrivId2Changing(value);
					this.SendPropertyChanging();
					this._PrivId2 = value;
					this.SendPropertyChanged("PrivId2");
					this.OnPrivId2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostPriv", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string PostPriv
		{
			get
			{
				return this._PostPriv;
			}
			set
			{
				if ((this._PostPriv != value))
				{
					this.OnPostPrivChanging(value);
					this.SendPropertyChanging();
					this._PostPriv = value;
					this.SendPropertyChanged("PostPriv");
					this.OnPostPrivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostDept", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string PostDept
		{
			get
			{
				return this._PostDept;
			}
			set
			{
				if ((this._PostDept != value))
				{
					this.OnPostDeptChanging(value);
					this.SendPropertyChanging();
					this._PostDept = value;
					this.SendPropertyChanged("PostDept");
					this.OnPostDeptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptId", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DeptId
		{
			get
			{
				return this._DeptId;
			}
			set
			{
				if ((this._DeptId != value))
				{
					this.OnDeptIdChanging(value);
					this.SendPropertyChanging();
					this._DeptId = value;
					this.SendPropertyChanged("DeptId");
					this.OnDeptIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptId2", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string DeptId2
		{
			get
			{
				return this._DeptId2;
			}
			set
			{
				if ((this._DeptId2 != value))
				{
					this.OnDeptId2Changing(value);
					this.SendPropertyChanging();
					this._DeptId2 = value;
					this.SendPropertyChanged("DeptId2");
					this.OnDeptId2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanBroadcast", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> CanBroadcast
		{
			get
			{
				return this._CanBroadcast;
			}
			set
			{
				if ((this._CanBroadcast != value))
				{
					this.OnCanBroadcastChanging(value);
					this.SendPropertyChanging();
					this._CanBroadcast = value;
					this.SendPropertyChanged("CanBroadcast");
					this.OnCanBroadcastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthday", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> Birthday
		{
			get
			{
				return this._Birthday;
			}
			set
			{
				if ((this._Birthday != value))
				{
					this.OnBirthdayChanging(value);
					this.SendPropertyChanging();
					this._Birthday = value;
					this.SendPropertyChanged("Birthday");
					this.OnBirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHideBirthday", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> IsHideBirthday
		{
			get
			{
				return this._IsHideBirthday;
			}
			set
			{
				if ((this._IsHideBirthday != value))
				{
					this.OnIsHideBirthdayChanging(value);
					this.SendPropertyChanging();
					this._IsHideBirthday = value;
					this.SendPropertyChanged("IsHideBirthday");
					this.OnIsHideBirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelNoDept", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string TelNoDept
		{
			get
			{
				return this._TelNoDept;
			}
			set
			{
				if ((this._TelNoDept != value))
				{
					this.OnTelNoDeptChanging(value);
					this.SendPropertyChanging();
					this._TelNoDept = value;
					this.SendPropertyChanged("TelNoDept");
					this.OnTelNoDeptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaxNoDept", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string FaxNoDept
		{
			get
			{
				return this._FaxNoDept;
			}
			set
			{
				if ((this._FaxNoDept != value))
				{
					this.OnFaxNoDeptChanging(value);
					this.SendPropertyChanging();
					this._FaxNoDept = value;
					this.SendPropertyChanged("FaxNoDept");
					this.OnFaxNoDeptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressHome", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string AddressHome
		{
			get
			{
				return this._AddressHome;
			}
			set
			{
				if ((this._AddressHome != value))
				{
					this.OnAddressHomeChanging(value);
					this.SendPropertyChanging();
					this._AddressHome = value;
					this.SendPropertyChanged("AddressHome");
					this.OnAddressHomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipHome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string ZipHome
		{
			get
			{
				return this._ZipHome;
			}
			set
			{
				if ((this._ZipHome != value))
				{
					this.OnZipHomeChanging(value);
					this.SendPropertyChanging();
					this._ZipHome = value;
					this.SendPropertyChanged("ZipHome");
					this.OnZipHomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelHome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string TelHome
		{
			get
			{
				return this._TelHome;
			}
			set
			{
				if ((this._TelHome != value))
				{
					this.OnTelHomeChanging(value);
					this.SendPropertyChanging();
					this._TelHome = value;
					this.SendPropertyChanged("TelHome");
					this.OnTelHomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHideMobile", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> IsHideMobile
		{
			get
			{
				return this._IsHideMobile;
			}
			set
			{
				if ((this._IsHideMobile != value))
				{
					this.OnIsHideMobileChanging(value);
					this.SendPropertyChanging();
					this._IsHideMobile = value;
					this.SendPropertyChanged("IsHideMobile");
					this.OnIsHideMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bp", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Bp
		{
			get
			{
				return this._Bp;
			}
			set
			{
				if ((this._Bp != value))
				{
					this.OnBpChanging(value);
					this.SendPropertyChanging();
					this._Bp = value;
					this.SendPropertyChanged("Bp");
					this.OnBpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oicq", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string Oicq
		{
			get
			{
				return this._Oicq;
			}
			set
			{
				if ((this._Oicq != value))
				{
					this.OnOicqChanging(value);
					this.SendPropertyChanging();
					this._Oicq = value;
					this.SendPropertyChanged("Oicq");
					this.OnOicqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icq", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string Icq
		{
			get
			{
				return this._Icq;
			}
			set
			{
				if ((this._Icq != value))
				{
					this.OnIcqChanging(value);
					this.SendPropertyChanging();
					this._Icq = value;
					this.SendPropertyChanged("Icq");
					this.OnIcqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Msn", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Msn
		{
			get
			{
				return this._Msn;
			}
			set
			{
				if ((this._Msn != value))
				{
					this.OnMsnChanging(value);
					this.SendPropertyChanging();
					this._Msn = value;
					this.SendPropertyChanged("Msn");
					this.OnMsnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skype", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Skype
		{
			get
			{
				return this._Skype;
			}
			set
			{
				if ((this._Skype != value))
				{
					this.OnSkypeChanging(value);
					this.SendPropertyChanging();
					this._Skype = value;
					this.SendPropertyChanged("Skype");
					this.OnSkypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickName", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string NickName
		{
			get
			{
				return this._NickName;
			}
			set
			{
				if ((this._NickName != value))
				{
					this.OnNickNameChanging(value);
					this.SendPropertyChanging();
					this._NickName = value;
					this.SendPropertyChanged("NickName");
					this.OnNickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avatar", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Avatar
		{
			get
			{
				return this._Avatar;
			}
			set
			{
				if ((this._Avatar != value))
				{
					this.OnAvatarChanging(value);
					this.SendPropertyChanging();
					this._Avatar = value;
					this.SendPropertyChanged("Avatar");
					this.OnAvatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuType", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> MenuType
		{
			get
			{
				return this._MenuType;
			}
			set
			{
				if ((this._MenuType != value))
				{
					this.OnMenuTypeChanging(value);
					this.SendPropertyChanging();
					this._MenuType = value;
					this.SendPropertyChanged("MenuType");
					this.OnMenuTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuHide", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> MenuHide
		{
			get
			{
				return this._MenuHide;
			}
			set
			{
				if ((this._MenuHide != value))
				{
					this.OnMenuHideChanging(value);
					this.SendPropertyChanging();
					this._MenuHide = value;
					this.SendPropertyChanged("MenuHide");
					this.OnMenuHideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmsOn", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> SmsOn
		{
			get
			{
				return this._SmsOn;
			}
			set
			{
				if ((this._SmsOn != value))
				{
					this.OnSmsOnChanging(value);
					this.SendPropertyChanging();
					this._SmsOn = value;
					this.SendPropertyChanged("SmsOn");
					this.OnSmsOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallSound", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> CallSound
		{
			get
			{
				return this._CallSound;
			}
			set
			{
				if ((this._CallSound != value))
				{
					this.OnCallSoundChanging(value);
					this.SendPropertyChanging();
					this._CallSound = value;
					this.SendPropertyChanged("CallSound");
					this.OnCallSoundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Theme", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Theme
		{
			get
			{
				return this._Theme;
			}
			set
			{
				if ((this._Theme != value))
				{
					this.OnThemeChanging(value);
					this.SendPropertyChanging();
					this._Theme = value;
					this.SendPropertyChanged("Theme");
					this.OnThemeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MytableLeft", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string MytableLeft
		{
			get
			{
				return this._MytableLeft;
			}
			set
			{
				if ((this._MytableLeft != value))
				{
					this.OnMytableLeftChanging(value);
					this.SendPropertyChanging();
					this._MytableLeft = value;
					this.SendPropertyChanged("MytableLeft");
					this.OnMytableLeftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MytableRight", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string MytableRight
		{
			get
			{
				return this._MytableRight;
			}
			set
			{
				if ((this._MytableRight != value))
				{
					this.OnMytableRightChanging(value);
					this.SendPropertyChanging();
					this._MytableRight = value;
					this.SendPropertyChanged("MytableRight");
					this.OnMytableRightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailCapacity", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> EmailCapacity
		{
			get
			{
				return this._EmailCapacity;
			}
			set
			{
				if ((this._EmailCapacity != value))
				{
					this.OnEmailCapacityChanging(value);
					this.SendPropertyChanging();
					this._EmailCapacity = value;
					this.SendPropertyChanged("EmailCapacity");
					this.OnEmailCapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderCapacity", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> FolderCapacity
		{
			get
			{
				return this._FolderCapacity;
			}
			set
			{
				if ((this._FolderCapacity != value))
				{
					this.OnFolderCapacityChanging(value);
					this.SendPropertyChanging();
					this._FolderCapacity = value;
					this.SendPropertyChanged("FolderCapacity");
					this.OnFolderCapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnlineTime", DbType="Real", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<float> OnlineTime
		{
			get
			{
				return this._OnlineTime;
			}
			set
			{
				if ((this._OnlineTime != value))
				{
					this.OnOnlineTimeChanging(value);
					this.SendPropertyChanging();
					this._OnlineTime = value;
					this.SendPropertyChanged("OnlineTime");
					this.OnOnlineTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DutyType", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DutyType
		{
			get
			{
				return this._DutyType;
			}
			set
			{
				if ((this._DutyType != value))
				{
					this.OnDutyTypeChanging(value);
					this.SendPropertyChanging();
					this._DutyType = value;
					this.SendPropertyChanged("DutyType");
					this.OnDutyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendCard", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string AttendCard
		{
			get
			{
				return this._AttendCard;
			}
			set
			{
				if ((this._AttendCard != value))
				{
					this.OnAttendCardChanging(value);
					this.SendPropertyChanging();
					this._AttendCard = value;
					this.SendPropertyChanged("AttendCard");
					this.OnAttendCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPassTime", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime LastPassTime
		{
			get
			{
				return this._LastPassTime;
			}
			set
			{
				if ((this._LastPassTime != value))
				{
					this.OnLastPassTimeChanging(value);
					this.SendPropertyChanging();
					this._LastPassTime = value;
					this.SendPropertyChanged("LastPassTime");
					this.OnLastPassTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastVisitTime", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime LastVisitTime
		{
			get
			{
				return this._LastVisitTime;
			}
			set
			{
				if ((this._LastVisitTime != value))
				{
					this.OnLastVisitTimeChanging(value);
					this.SendPropertyChanging();
					this._LastVisitTime = value;
					this.SendPropertyChanged("LastVisitTime");
					this.OnLastVisitTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastIp", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string LastIp
		{
			get
			{
				return this._LastIp;
			}
			set
			{
				if ((this._LastIp != value))
				{
					this.OnLastIpChanging(value);
					this.SendPropertyChanging();
					this._LastIp = value;
					this.SendPropertyChanged("LastIp");
					this.OnLastIpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disabled", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Disabled
		{
			get
			{
				return this._Disabled;
			}
			set
			{
				if ((this._Disabled != value))
				{
					this.OnDisabledChanging(value);
					this.SendPropertyChanging();
					this._Disabled = value;
					this.SendPropertyChanged("Disabled");
					this.OnDisabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BindIp", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string BindIp
		{
			get
			{
				return this._BindIp;
			}
			set
			{
				if ((this._BindIp != value))
				{
					this.OnBindIpChanging(value);
					this.SendPropertyChanging();
					this._BindIp = value;
					this.SendPropertyChanged("BindIp");
					this.OnBindIpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsingKey", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> UsingKey
		{
			get
			{
				return this._UsingKey;
			}
			set
			{
				if ((this._UsingKey != value))
				{
					this.OnUsingKeyChanging(value);
					this.SendPropertyChanging();
					this._UsingKey = value;
					this.SendPropertyChanged("UsingKey");
					this.OnUsingKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UGuid", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string UGuid
		{
			get
			{
				return this._UGuid;
			}
			set
			{
				if ((this._UGuid != value))
				{
					this.OnUGuidChanging(value);
					this.SendPropertyChanging();
					this._UGuid = value;
					this.SendPropertyChanged("UGuid");
					this.OnUGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UKey", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string UKey
		{
			get
			{
				return this._UKey;
			}
			set
			{
				if ((this._UKey != value))
				{
					this.OnUKeyChanging(value);
					this.SendPropertyChanging();
					this._UKey = value;
					this.SendPropertyChanged("UKey");
					this.OnUKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UExt", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string UExt
		{
			get
			{
				return this._UExt;
			}
			set
			{
				if ((this._UExt != value))
				{
					this.OnUExtChanging(value);
					this.SendPropertyChanging();
					this._UExt = value;
					this.SendPropertyChanged("UExt");
					this.OnUExtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotUser", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> NotUser
		{
			get
			{
				return this._NotUser;
			}
			set
			{
				if ((this._NotUser != value))
				{
					this.OnNotUserChanging(value);
					this.SendPropertyChanging();
					this._NotUser = value;
					this.SendPropertyChanged("NotUser");
					this.OnNotUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotTable", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> NotTable
		{
			get
			{
				return this._NotTable;
			}
			set
			{
				if ((this._NotTable != value))
				{
					this.OnNotTableChanging(value);
					this.SendPropertyChanging();
					this._NotTable = value;
					this.SendPropertyChanged("NotTable");
					this.OnNotTableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultMenu", DbType="NVarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string DefaultMenu
		{
			get
			{
				return this._DefaultMenu;
			}
			set
			{
				if ((this._DefaultMenu != value))
				{
					this.OnDefaultMenuChanging(value);
					this.SendPropertyChanging();
					this._DefaultMenu = value;
					this.SendPropertyChanged("DefaultMenu");
					this.OnDefaultMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TablePhoto", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string TablePhoto
		{
			get
			{
				return this._TablePhoto;
			}
			set
			{
				if ((this._TablePhoto != value))
				{
					this.OnTablePhotoChanging(value);
					this.SendPropertyChanging();
					this._TablePhoto = value;
					this.SendPropertyChanged("TablePhoto");
					this.OnTablePhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebmailNum", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> WebmailNum
		{
			get
			{
				return this._WebmailNum;
			}
			set
			{
				if ((this._WebmailNum != value))
				{
					this.OnWebmailNumChanging(value);
					this.SendPropertyChanging();
					this._WebmailNum = value;
					this.SendPropertyChanged("WebmailNum");
					this.OnWebmailNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebmailCapacity", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> WebmailCapacity
		{
			get
			{
				return this._WebmailCapacity;
			}
			set
			{
				if ((this._WebmailCapacity != value))
				{
					this.OnWebmailCapacityChanging(value);
					this.SendPropertyChanging();
					this._WebmailCapacity = value;
					this.SendPropertyChanged("WebmailCapacity");
					this.OnWebmailCapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdUserId", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string AdUserId
		{
			get
			{
				return this._AdUserId;
			}
			set
			{
				if ((this._AdUserId != value))
				{
					this.OnAdUserIdChanging(value);
					this.SendPropertyChanging();
					this._AdUserId = value;
					this.SendPropertyChanged("AdUserId");
					this.OnAdUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsingAd", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> UsingAd
		{
			get
			{
				return this._UsingAd;
			}
			set
			{
				if ((this._UsingAd != value))
				{
					this.OnUsingAdChanging(value);
					this.SendPropertyChanging();
					this._UsingAd = value;
					this.SendPropertyChanged("UsingAd");
					this.OnUsingAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModify", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary LastModify
		{
			get
			{
				return this._LastModify;
			}
			set
			{
				if ((this._LastModify != value))
				{
					this.OnLastModifyChanging(value);
					this.SendPropertyChanging();
					this._LastModify = value;
					this.SendPropertyChanged("LastModify");
					this.OnLastModifyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPosId", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> UserPosId
		{
			get
			{
				return this._UserPosId;
			}
			set
			{
				if ((this._UserPosId != value))
				{
					this.OnUserPosIdChanging(value);
					this.SendPropertyChanging();
					this._UserPosId = value;
					this.SendPropertyChanged("UserPosId");
					this.OnUserPosIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userrole", DbType="VarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string userrole
		{
			get
			{
				return this._userrole;
			}
			set
			{
				if ((this._userrole != value))
				{
					this.OnuserroleChanging(value);
					this.SendPropertyChanging();
					this._userrole = value;
					this.SendPropertyChanged("userrole");
					this.OnuserroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOBJID", DbType="Char(8)", UpdateCheck=UpdateCheck.Never)]
		public string SOBJID
		{
			get
			{
				return this._SOBJID;
			}
			set
			{
				if ((this._SOBJID != value))
				{
					this.OnSOBJIDChanging(value);
					this.SendPropertyChanging();
					this._SOBJID = value;
					this.SendPropertyChanged("SOBJID");
					this.OnSOBJIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAT2", DbType="Char(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<char> STAT2
		{
			get
			{
				return this._STAT2;
			}
			set
			{
				if ((this._STAT2 != value))
				{
					this.OnSTAT2Changing(value);
					this.SendPropertyChanging();
					this._STAT2 = value;
					this.SendPropertyChanged("STAT2");
					this.OnSTAT2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISTAT", DbType="Char(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<char> ISTAT
		{
			get
			{
				return this._ISTAT;
			}
			set
			{
				if ((this._ISTAT != value))
				{
					this.OnISTATChanging(value);
					this.SendPropertyChanging();
					this._ISTAT = value;
					this.SendPropertyChanged("ISTAT");
					this.OnISTATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOSTL", DbType="Char(10)", UpdateCheck=UpdateCheck.Never)]
		public string KOSTL
		{
			get
			{
				return this._KOSTL;
			}
			set
			{
				if ((this._KOSTL != value))
				{
					this.OnKOSTLChanging(value);
					this.SendPropertyChanging();
					this._KOSTL = value;
					this.SendPropertyChanged("KOSTL");
					this.OnKOSTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUKRS", DbType="Char(4)", UpdateCheck=UpdateCheck.Never)]
		public string BUKRS
		{
			get
			{
				return this._BUKRS;
			}
			set
			{
				if ((this._BUKRS != value))
				{
					this.OnBUKRSChanging(value);
					this.SendPropertyChanging();
					this._BUKRS = value;
					this.SendPropertyChanged("BUKRS");
					this.OnBUKRSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WERKS", DbType="Char(4)", UpdateCheck=UpdateCheck.Never)]
		public string WERKS
		{
			get
			{
				return this._WERKS;
			}
			set
			{
				if ((this._WERKS != value))
				{
					this.OnWERKSChanging(value);
					this.SendPropertyChanging();
					this._WERKS = value;
					this.SendPropertyChanged("WERKS");
					this.OnWERKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERSG", DbType="Char(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<char> PERSG
		{
			get
			{
				return this._PERSG;
			}
			set
			{
				if ((this._PERSG != value))
				{
					this.OnPERSGChanging(value);
					this.SendPropertyChanging();
					this._PERSG = value;
					this.SendPropertyChanged("PERSG");
					this.OnPERSGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERSK", DbType="Char(2)", UpdateCheck=UpdateCheck.Never)]
		public string PERSK
		{
			get
			{
				return this._PERSK;
			}
			set
			{
				if ((this._PERSK != value))
				{
					this.OnPERSKChanging(value);
					this.SendPropertyChanging();
					this._PERSK = value;
					this.SendPropertyChanged("PERSK");
					this.OnPERSKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VDSK1", DbType="Char(14)", UpdateCheck=UpdateCheck.Never)]
		public string VDSK1
		{
			get
			{
				return this._VDSK1;
			}
			set
			{
				if ((this._VDSK1 != value))
				{
					this.OnVDSK1Changing(value);
					this.SendPropertyChanging();
					this._VDSK1 = value;
					this.SendPropertyChanged("VDSK1");
					this.OnVDSK1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GSBER", DbType="Char(4)", UpdateCheck=UpdateCheck.Never)]
		public string GSBER
		{
			get
			{
				return this._GSBER;
			}
			set
			{
				if ((this._GSBER != value))
				{
					this.OnGSBERChanging(value);
					this.SendPropertyChanging();
					this._GSBER = value;
					this.SendPropertyChanged("GSBER");
					this.OnGSBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BTRTL", DbType="Char(4)", UpdateCheck=UpdateCheck.Never)]
		public string BTRTL
		{
			get
			{
				return this._BTRTL;
			}
			set
			{
				if ((this._BTRTL != value))
				{
					this.OnBTRTLChanging(value);
					this.SendPropertyChanging();
					this._BTRTL = value;
					this.SendPropertyChanged("BTRTL");
					this.OnBTRTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABKRS", DbType="Char(2)", UpdateCheck=UpdateCheck.Never)]
		public string ABKRS
		{
			get
			{
				return this._ABKRS;
			}
			set
			{
				if ((this._ABKRS != value))
				{
					this.OnABKRSChanging(value);
					this.SendPropertyChanging();
					this._ABKRS = value;
					this.SendPropertyChanged("ABKRS");
					this.OnABKRSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STELL", DbType="Char(8)", UpdateCheck=UpdateCheck.Never)]
		public string STELL
		{
			get
			{
				return this._STELL;
			}
			set
			{
				if ((this._STELL != value))
				{
					this.OnSTELLChanging(value);
					this.SendPropertyChanging();
					this._STELL = value;
					this.SendPropertyChanged("STELL");
					this.OnSTELLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBMOD", DbType="Char(4)", UpdateCheck=UpdateCheck.Never)]
		public string SBMOD
		{
			get
			{
				return this._SBMOD;
			}
			set
			{
				if ((this._SBMOD != value))
				{
					this.OnSBMODChanging(value);
					this.SendPropertyChanging();
					this._SBMOD = value;
					this.SendPropertyChanged("SBMOD");
					this.OnSBMODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICNUM", DbType="NVarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string ICNUM
		{
			get
			{
				return this._ICNUM;
			}
			set
			{
				if ((this._ICNUM != value))
				{
					this.OnICNUMChanging(value);
					this.SendPropertyChanging();
					this._ICNUM = value;
					this.SendPropertyChanged("ICNUM");
					this.OnICNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERCARD", DbType="NVarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string USERCARD
		{
			get
			{
				return this._USERCARD;
			}
			set
			{
				if ((this._USERCARD != value))
				{
					this.OnUSERCARDChanging(value);
					this.SendPropertyChanging();
					this._USERCARD = value;
					this.SendPropertyChanged("USERCARD");
					this.OnUSERCARDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users_Roles")]
	public partial class Users_Roles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _URID;
		
		private string _UserId;
		
		private System.Nullable<int> _RolesId;
		
		private System.Nullable<int> _Status;
		
		private string _Flag;
		
		private System.Data.Linq.Binary _LastModify;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnURIDChanging(int value);
    partial void OnURIDChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnRolesIdChanging(System.Nullable<int> value);
    partial void OnRolesIdChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnFlagChanging(string value);
    partial void OnFlagChanged();
    partial void OnLastModifyChanging(System.Data.Linq.Binary value);
    partial void OnLastModifyChanged();
    #endregion
		
		public Users_Roles()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int URID
		{
			get
			{
				return this._URID;
			}
			set
			{
				if ((this._URID != value))
				{
					this.OnURIDChanging(value);
					this.SendPropertyChanging();
					this._URID = value;
					this.SendPropertyChanged("URID");
					this.OnURIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RolesId", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> RolesId
		{
			get
			{
				return this._RolesId;
			}
			set
			{
				if ((this._RolesId != value))
				{
					this.OnRolesIdChanging(value);
					this.SendPropertyChanging();
					this._RolesId = value;
					this.SendPropertyChanged("RolesId");
					this.OnRolesIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="VarChar(4)", UpdateCheck=UpdateCheck.Never)]
		public string Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModify", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary LastModify
		{
			get
			{
				return this._LastModify;
			}
			set
			{
				if ((this._LastModify != value))
				{
					this.OnLastModifyChanging(value);
					this.SendPropertyChanging();
					this._LastModify = value;
					this.SendPropertyChanged("LastModify");
					this.OnLastModifyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_material_deliver_report")]
	public partial class V_material_deliver_report
	{
		
		private string _WERKS;
		
		private string _Werks_NAME;
		
		private string _UserId;
		
		private string _UserName;
		
		private string _Mobile;
		
		private string _dn_number;
		
		private string _equipment_number;
		
		private System.DateTime _deliver_time;
		
		private System.Nullable<System.DateTime> _receive_time;
		
		private string _state_delivery;
		
		public V_material_deliver_report()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WERKS", DbType="Char(4)")]
		public string WERKS
		{
			get
			{
				return this._WERKS;
			}
			set
			{
				if ((this._WERKS != value))
				{
					this._WERKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Werks_NAME", DbType="NVarChar(80)")]
		public string Werks_NAME
		{
			get
			{
				return this._Werks_NAME;
			}
			set
			{
				if ((this._Werks_NAME != value))
				{
					this._Werks_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(20)")]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(20)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dn_number", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string dn_number
		{
			get
			{
				return this._dn_number;
			}
			set
			{
				if ((this._dn_number != value))
				{
					this._dn_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipment_number", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string equipment_number
		{
			get
			{
				return this._equipment_number;
			}
			set
			{
				if ((this._equipment_number != value))
				{
					this._equipment_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deliver_time", DbType="DateTime NOT NULL")]
		public System.DateTime deliver_time
		{
			get
			{
				return this._deliver_time;
			}
			set
			{
				if ((this._deliver_time != value))
				{
					this._deliver_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receive_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> receive_time
		{
			get
			{
				return this._receive_time;
			}
			set
			{
				if ((this._receive_time != value))
				{
					this._receive_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_delivery", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string state_delivery
		{
			get
			{
				return this._state_delivery;
			}
			set
			{
				if ((this._state_delivery != value))
				{
					this._state_delivery = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
