<?xml version="1.0" encoding="utf-8"?><Database Name="HXOA" Class="HXOADBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.0.51.68;Initial Catalog=HXOA;Persist Security Info=True;User ID=sa" SettingsObjectName="DB.Properties.Settings" SettingsPropertyName="HXOAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Function_Setting" Member="Function_Setting">
    <Type Name="Function_Setting">
      <Column Name="fs_num" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fs_funcno" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fs_model" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fs_imageurl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="fs_funcname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fs_menuurl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="fs_active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fs_export" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fs_view" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fs_insert" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fs_update" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fs_delete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fs_status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fs_flag" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fs_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fs_pid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastmodify" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Role_Right" Member="Role_Right">
    <Type Name="Role_Right">
      <Column Name="ur_num" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ur_rolesid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ur_funcno" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ur_model" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ur_imageurl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ur_funcname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ur_menuurl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ur_active" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ur_export" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ur_view" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ur_insert" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ur_update" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ur_delete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ur_status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ur_flag" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ur_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ur_pid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastmodify" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Roles">
      <Column Name="RolesId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RolesName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="RoleType" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Flag" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LastModify" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users_Roles" Member="Users_Roles">
    <Type Name="Users_Roles">
      <Column Name="URID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RolesId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Flag" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="LastModify" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_material_deliver_report" Member="V_material_deliver_report">
    <Type Name="V_material_deliver_report">
      <Column Name="WERKS" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="Werks_NAME" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dn_number" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="equipment_number" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="deliver_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="receive_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="state_delivery" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UserId2" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UserNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PrivId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrivId2" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PostPriv" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostDept" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="DeptId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeptId2" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CanBroadcast" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsHideBirthday" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TelNoDept" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FaxNoDept" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AddressHome" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ZipHome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TelHome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsHideMobile" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Oicq" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Icq" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Msn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Skype" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuHide" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SmsOn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CallSound" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Theme" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="MytableLeft" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MytableRight" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="EmailCapacity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FolderCapacity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OnlineTime" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="DutyType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttendCard" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastPassTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastVisitTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastIp" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Disabled" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BindIp" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="UsingKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UGuid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UKey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UExt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NotUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NotTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DefaultMenu" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TablePhoto" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WebmailNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WebmailCapacity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdUserId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UsingAd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModify" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="UserPosId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="userrole" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SOBJID" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="STAT2" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ISTAT" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="KOSTL" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="BUKRS" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="WERKS" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="PERSG" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PERSK" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="VDSK1" Type="System.String" DbType="Char(14)" CanBeNull="true" />
      <Column Name="GSBER" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="BTRTL" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="ABKRS" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="STELL" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="SBMOD" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="ICNUM" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="USERCARD" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_HR_SAP_WERKS" Member="T_HR_SAP_WERKS">
    <Type Name="T_HR_SAP_WERKS">
      <Column Name="WID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WERKS" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="NAME1" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="STATS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="INPRO" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="BZIRK" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="BZIRK2" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="LOWPAY" Type="System.Decimal" DbType="Decimal(13,2)" CanBeNull="true" />
      <Column Name="RLOWPAY" Type="System.Decimal" DbType="Decimal(13,2)" CanBeNull="true" />
      <Column Name="BUKRS" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="KHINR" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AREA" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="PITIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CHAGEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CHAGEUSER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModify" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="EROED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NEWSTORE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZTYPE" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="Col1" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Col2" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Col3" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Col4" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Col5" Type="System.String" DbType="NVarChar(120)" CanBeNull="true" />
      <Column Name="Col6" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Col7" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Col8" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Col9" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Col10" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>