#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HXOA")]
	public partial class HRMDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertUsers(Users instance);
    partial void UpdateUsers(Users instance);
    partial void DeleteUsers(Users instance);
    #endregion
		
		public HRMDBDataContext() : 
				base(global::DLL.Properties.Settings.Default.HXOAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HRMDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRMDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRMDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRMDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Users> Users
		{
			get
			{
				return this.GetTable<Users>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _UserId;
		
		private string _UserId2;
		
		private System.Nullable<int> _UserNo;
		
		private string _UserName;
		
		private string _Password;
		
		private System.Nullable<int> _PrivId;
		
		private string _PrivId2;
		
		private string _PostPriv;
		
		private string _PostDept;
		
		private System.Nullable<int> _DeptId;
		
		private string _DeptId2;
		
		private System.Nullable<int> _CanBroadcast;
		
		private System.Nullable<int> _Sex;
		
		private System.Nullable<System.DateTime> _Birthday;
		
		private System.Nullable<int> _IsHideBirthday;
		
		private string _TelNoDept;
		
		private string _FaxNoDept;
		
		private string _AddressHome;
		
		private string _ZipHome;
		
		private string _TelHome;
		
		private string _Mobile;
		
		private System.Nullable<int> _IsHideMobile;
		
		private string _Bp;
		
		private string _Email;
		
		private string _Oicq;
		
		private string _Icq;
		
		private string _Msn;
		
		private string _Skype;
		
		private System.Data.Linq.Binary _Photo;
		
		private string _NickName;
		
		private System.Nullable<int> _Avatar;
		
		private System.Nullable<int> _MenuType;
		
		private System.Nullable<int> _MenuHide;
		
		private System.Nullable<int> _SmsOn;
		
		private System.Nullable<int> _CallSound;
		
		private System.Nullable<int> _Theme;
		
		private string _Note;
		
		private string _MytableLeft;
		
		private string _MytableRight;
		
		private System.Nullable<int> _EmailCapacity;
		
		private System.Nullable<int> _FolderCapacity;
		
		private System.Nullable<float> _OnlineTime;
		
		private System.Nullable<int> _DutyType;
		
		private string _AttendCard;
		
		private System.Nullable<int> _State;
		
		private System.DateTime _LastPassTime;
		
		private System.DateTime _LastVisitTime;
		
		private string _LastIp;
		
		private System.Nullable<int> _Disabled;
		
		private string _BindIp;
		
		private System.Nullable<int> _UsingKey;
		
		private string _UGuid;
		
		private string _UKey;
		
		private string _UExt;
		
		private System.Nullable<int> _NotUser;
		
		private System.Nullable<int> _NotTable;
		
		private string _DefaultMenu;
		
		private string _TablePhoto;
		
		private System.Nullable<int> _WebmailNum;
		
		private System.Nullable<int> _WebmailCapacity;
		
		private string _AdUserId;
		
		private System.Nullable<int> _UsingAd;
		
		private System.Data.Linq.Binary _LastModify;
		
		private System.Nullable<int> _UserPosId;
		
		private string _userrole;
		
		private string _SOBJID;
		
		private System.Nullable<char> _STAT2;
		
		private System.Nullable<char> _ISTAT;
		
		private string _KOSTL;
		
		private string _BUKRS;
		
		private string _WERKS;
		
		private System.Nullable<char> _PERSG;
		
		private string _PERSK;
		
		private string _VDSK1;
		
		private string _GSBER;
		
		private string _BTRTL;
		
		private string _ABKRS;
		
		private string _STELL;
		
		private string _SBMOD;
		
		private string _ICNUM;
		
		private string _USERCARD;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnUserId2Changing(string value);
    partial void OnUserId2Changed();
    partial void OnUserNoChanging(System.Nullable<int> value);
    partial void OnUserNoChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPrivIdChanging(System.Nullable<int> value);
    partial void OnPrivIdChanged();
    partial void OnPrivId2Changing(string value);
    partial void OnPrivId2Changed();
    partial void OnPostPrivChanging(string value);
    partial void OnPostPrivChanged();
    partial void OnPostDeptChanging(string value);
    partial void OnPostDeptChanged();
    partial void OnDeptIdChanging(System.Nullable<int> value);
    partial void OnDeptIdChanged();
    partial void OnDeptId2Changing(string value);
    partial void OnDeptId2Changed();
    partial void OnCanBroadcastChanging(System.Nullable<int> value);
    partial void OnCanBroadcastChanged();
    partial void OnSexChanging(System.Nullable<int> value);
    partial void OnSexChanged();
    partial void OnBirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthdayChanged();
    partial void OnIsHideBirthdayChanging(System.Nullable<int> value);
    partial void OnIsHideBirthdayChanged();
    partial void OnTelNoDeptChanging(string value);
    partial void OnTelNoDeptChanged();
    partial void OnFaxNoDeptChanging(string value);
    partial void OnFaxNoDeptChanged();
    partial void OnAddressHomeChanging(string value);
    partial void OnAddressHomeChanged();
    partial void OnZipHomeChanging(string value);
    partial void OnZipHomeChanged();
    partial void OnTelHomeChanging(string value);
    partial void OnTelHomeChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnIsHideMobileChanging(System.Nullable<int> value);
    partial void OnIsHideMobileChanged();
    partial void OnBpChanging(string value);
    partial void OnBpChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnOicqChanging(string value);
    partial void OnOicqChanged();
    partial void OnIcqChanging(string value);
    partial void OnIcqChanged();
    partial void OnMsnChanging(string value);
    partial void OnMsnChanged();
    partial void OnSkypeChanging(string value);
    partial void OnSkypeChanged();
    partial void OnPhotoChanging(System.Data.Linq.Binary value);
    partial void OnPhotoChanged();
    partial void OnNickNameChanging(string value);
    partial void OnNickNameChanged();
    partial void OnAvatarChanging(System.Nullable<int> value);
    partial void OnAvatarChanged();
    partial void OnMenuTypeChanging(System.Nullable<int> value);
    partial void OnMenuTypeChanged();
    partial void OnMenuHideChanging(System.Nullable<int> value);
    partial void OnMenuHideChanged();
    partial void OnSmsOnChanging(System.Nullable<int> value);
    partial void OnSmsOnChanged();
    partial void OnCallSoundChanging(System.Nullable<int> value);
    partial void OnCallSoundChanged();
    partial void OnThemeChanging(System.Nullable<int> value);
    partial void OnThemeChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnMytableLeftChanging(string value);
    partial void OnMytableLeftChanged();
    partial void OnMytableRightChanging(string value);
    partial void OnMytableRightChanged();
    partial void OnEmailCapacityChanging(System.Nullable<int> value);
    partial void OnEmailCapacityChanged();
    partial void OnFolderCapacityChanging(System.Nullable<int> value);
    partial void OnFolderCapacityChanged();
    partial void OnOnlineTimeChanging(System.Nullable<float> value);
    partial void OnOnlineTimeChanged();
    partial void OnDutyTypeChanging(System.Nullable<int> value);
    partial void OnDutyTypeChanged();
    partial void OnAttendCardChanging(string value);
    partial void OnAttendCardChanged();
    partial void OnStateChanging(System.Nullable<int> value);
    partial void OnStateChanged();
    partial void OnLastPassTimeChanging(System.DateTime value);
    partial void OnLastPassTimeChanged();
    partial void OnLastVisitTimeChanging(System.DateTime value);
    partial void OnLastVisitTimeChanged();
    partial void OnLastIpChanging(string value);
    partial void OnLastIpChanged();
    partial void OnDisabledChanging(System.Nullable<int> value);
    partial void OnDisabledChanged();
    partial void OnBindIpChanging(string value);
    partial void OnBindIpChanged();
    partial void OnUsingKeyChanging(System.Nullable<int> value);
    partial void OnUsingKeyChanged();
    partial void OnUGuidChanging(string value);
    partial void OnUGuidChanged();
    partial void OnUKeyChanging(string value);
    partial void OnUKeyChanged();
    partial void OnUExtChanging(string value);
    partial void OnUExtChanged();
    partial void OnNotUserChanging(System.Nullable<int> value);
    partial void OnNotUserChanged();
    partial void OnNotTableChanging(System.Nullable<int> value);
    partial void OnNotTableChanged();
    partial void OnDefaultMenuChanging(string value);
    partial void OnDefaultMenuChanged();
    partial void OnTablePhotoChanging(string value);
    partial void OnTablePhotoChanged();
    partial void OnWebmailNumChanging(System.Nullable<int> value);
    partial void OnWebmailNumChanged();
    partial void OnWebmailCapacityChanging(System.Nullable<int> value);
    partial void OnWebmailCapacityChanged();
    partial void OnAdUserIdChanging(string value);
    partial void OnAdUserIdChanged();
    partial void OnUsingAdChanging(System.Nullable<int> value);
    partial void OnUsingAdChanged();
    partial void OnLastModifyChanging(System.Data.Linq.Binary value);
    partial void OnLastModifyChanged();
    partial void OnUserPosIdChanging(System.Nullable<int> value);
    partial void OnUserPosIdChanged();
    partial void OnuserroleChanging(string value);
    partial void OnuserroleChanged();
    partial void OnSOBJIDChanging(string value);
    partial void OnSOBJIDChanged();
    partial void OnSTAT2Changing(System.Nullable<char> value);
    partial void OnSTAT2Changed();
    partial void OnISTATChanging(System.Nullable<char> value);
    partial void OnISTATChanged();
    partial void OnKOSTLChanging(string value);
    partial void OnKOSTLChanged();
    partial void OnBUKRSChanging(string value);
    partial void OnBUKRSChanged();
    partial void OnWERKSChanging(string value);
    partial void OnWERKSChanged();
    partial void OnPERSGChanging(System.Nullable<char> value);
    partial void OnPERSGChanged();
    partial void OnPERSKChanging(string value);
    partial void OnPERSKChanged();
    partial void OnVDSK1Changing(string value);
    partial void OnVDSK1Changed();
    partial void OnGSBERChanging(string value);
    partial void OnGSBERChanged();
    partial void OnBTRTLChanging(string value);
    partial void OnBTRTLChanged();
    partial void OnABKRSChanging(string value);
    partial void OnABKRSChanged();
    partial void OnSTELLChanging(string value);
    partial void OnSTELLChanged();
    partial void OnSBMODChanging(string value);
    partial void OnSBMODChanged();
    partial void OnICNUMChanging(string value);
    partial void OnICNUMChanged();
    partial void OnUSERCARDChanging(string value);
    partial void OnUSERCARDChanged();
    #endregion
		
		public Users()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId2", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string UserId2
		{
			get
			{
				return this._UserId2;
			}
			set
			{
				if ((this._UserId2 != value))
				{
					this.OnUserId2Changing(value);
					this.SendPropertyChanging();
					this._UserId2 = value;
					this.SendPropertyChanged("UserId2");
					this.OnUserId2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNo", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> UserNo
		{
			get
			{
				return this._UserNo;
			}
			set
			{
				if ((this._UserNo != value))
				{
					this.OnUserNoChanging(value);
					this.SendPropertyChanging();
					this._UserNo = value;
					this.SendPropertyChanged("UserNo");
					this.OnUserNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrivId", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> PrivId
		{
			get
			{
				return this._PrivId;
			}
			set
			{
				if ((this._PrivId != value))
				{
					this.OnPrivIdChanging(value);
					this.SendPropertyChanging();
					this._PrivId = value;
					this.SendPropertyChanged("PrivId");
					this.OnPrivIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrivId2", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string PrivId2
		{
			get
			{
				return this._PrivId2;
			}
			set
			{
				if ((this._PrivId2 != value))
				{
					this.OnPrivId2Changing(value);
					this.SendPropertyChanging();
					this._PrivId2 = value;
					this.SendPropertyChanged("PrivId2");
					this.OnPrivId2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostPriv", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string PostPriv
		{
			get
			{
				return this._PostPriv;
			}
			set
			{
				if ((this._PostPriv != value))
				{
					this.OnPostPrivChanging(value);
					this.SendPropertyChanging();
					this._PostPriv = value;
					this.SendPropertyChanged("PostPriv");
					this.OnPostPrivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostDept", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string PostDept
		{
			get
			{
				return this._PostDept;
			}
			set
			{
				if ((this._PostDept != value))
				{
					this.OnPostDeptChanging(value);
					this.SendPropertyChanging();
					this._PostDept = value;
					this.SendPropertyChanged("PostDept");
					this.OnPostDeptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptId", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DeptId
		{
			get
			{
				return this._DeptId;
			}
			set
			{
				if ((this._DeptId != value))
				{
					this.OnDeptIdChanging(value);
					this.SendPropertyChanging();
					this._DeptId = value;
					this.SendPropertyChanged("DeptId");
					this.OnDeptIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptId2", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string DeptId2
		{
			get
			{
				return this._DeptId2;
			}
			set
			{
				if ((this._DeptId2 != value))
				{
					this.OnDeptId2Changing(value);
					this.SendPropertyChanging();
					this._DeptId2 = value;
					this.SendPropertyChanged("DeptId2");
					this.OnDeptId2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanBroadcast", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> CanBroadcast
		{
			get
			{
				return this._CanBroadcast;
			}
			set
			{
				if ((this._CanBroadcast != value))
				{
					this.OnCanBroadcastChanging(value);
					this.SendPropertyChanging();
					this._CanBroadcast = value;
					this.SendPropertyChanged("CanBroadcast");
					this.OnCanBroadcastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthday", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> Birthday
		{
			get
			{
				return this._Birthday;
			}
			set
			{
				if ((this._Birthday != value))
				{
					this.OnBirthdayChanging(value);
					this.SendPropertyChanging();
					this._Birthday = value;
					this.SendPropertyChanged("Birthday");
					this.OnBirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHideBirthday", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> IsHideBirthday
		{
			get
			{
				return this._IsHideBirthday;
			}
			set
			{
				if ((this._IsHideBirthday != value))
				{
					this.OnIsHideBirthdayChanging(value);
					this.SendPropertyChanging();
					this._IsHideBirthday = value;
					this.SendPropertyChanged("IsHideBirthday");
					this.OnIsHideBirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelNoDept", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string TelNoDept
		{
			get
			{
				return this._TelNoDept;
			}
			set
			{
				if ((this._TelNoDept != value))
				{
					this.OnTelNoDeptChanging(value);
					this.SendPropertyChanging();
					this._TelNoDept = value;
					this.SendPropertyChanged("TelNoDept");
					this.OnTelNoDeptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaxNoDept", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string FaxNoDept
		{
			get
			{
				return this._FaxNoDept;
			}
			set
			{
				if ((this._FaxNoDept != value))
				{
					this.OnFaxNoDeptChanging(value);
					this.SendPropertyChanging();
					this._FaxNoDept = value;
					this.SendPropertyChanged("FaxNoDept");
					this.OnFaxNoDeptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressHome", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string AddressHome
		{
			get
			{
				return this._AddressHome;
			}
			set
			{
				if ((this._AddressHome != value))
				{
					this.OnAddressHomeChanging(value);
					this.SendPropertyChanging();
					this._AddressHome = value;
					this.SendPropertyChanged("AddressHome");
					this.OnAddressHomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZipHome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string ZipHome
		{
			get
			{
				return this._ZipHome;
			}
			set
			{
				if ((this._ZipHome != value))
				{
					this.OnZipHomeChanging(value);
					this.SendPropertyChanging();
					this._ZipHome = value;
					this.SendPropertyChanged("ZipHome");
					this.OnZipHomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelHome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string TelHome
		{
			get
			{
				return this._TelHome;
			}
			set
			{
				if ((this._TelHome != value))
				{
					this.OnTelHomeChanging(value);
					this.SendPropertyChanging();
					this._TelHome = value;
					this.SendPropertyChanged("TelHome");
					this.OnTelHomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHideMobile", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> IsHideMobile
		{
			get
			{
				return this._IsHideMobile;
			}
			set
			{
				if ((this._IsHideMobile != value))
				{
					this.OnIsHideMobileChanging(value);
					this.SendPropertyChanging();
					this._IsHideMobile = value;
					this.SendPropertyChanged("IsHideMobile");
					this.OnIsHideMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bp", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Bp
		{
			get
			{
				return this._Bp;
			}
			set
			{
				if ((this._Bp != value))
				{
					this.OnBpChanging(value);
					this.SendPropertyChanging();
					this._Bp = value;
					this.SendPropertyChanged("Bp");
					this.OnBpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oicq", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string Oicq
		{
			get
			{
				return this._Oicq;
			}
			set
			{
				if ((this._Oicq != value))
				{
					this.OnOicqChanging(value);
					this.SendPropertyChanging();
					this._Oicq = value;
					this.SendPropertyChanged("Oicq");
					this.OnOicqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icq", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string Icq
		{
			get
			{
				return this._Icq;
			}
			set
			{
				if ((this._Icq != value))
				{
					this.OnIcqChanging(value);
					this.SendPropertyChanging();
					this._Icq = value;
					this.SendPropertyChanged("Icq");
					this.OnIcqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Msn", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Msn
		{
			get
			{
				return this._Msn;
			}
			set
			{
				if ((this._Msn != value))
				{
					this.OnMsnChanging(value);
					this.SendPropertyChanging();
					this._Msn = value;
					this.SendPropertyChanged("Msn");
					this.OnMsnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skype", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Skype
		{
			get
			{
				return this._Skype;
			}
			set
			{
				if ((this._Skype != value))
				{
					this.OnSkypeChanging(value);
					this.SendPropertyChanging();
					this._Skype = value;
					this.SendPropertyChanged("Skype");
					this.OnSkypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickName", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string NickName
		{
			get
			{
				return this._NickName;
			}
			set
			{
				if ((this._NickName != value))
				{
					this.OnNickNameChanging(value);
					this.SendPropertyChanging();
					this._NickName = value;
					this.SendPropertyChanged("NickName");
					this.OnNickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avatar", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Avatar
		{
			get
			{
				return this._Avatar;
			}
			set
			{
				if ((this._Avatar != value))
				{
					this.OnAvatarChanging(value);
					this.SendPropertyChanging();
					this._Avatar = value;
					this.SendPropertyChanged("Avatar");
					this.OnAvatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuType", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> MenuType
		{
			get
			{
				return this._MenuType;
			}
			set
			{
				if ((this._MenuType != value))
				{
					this.OnMenuTypeChanging(value);
					this.SendPropertyChanging();
					this._MenuType = value;
					this.SendPropertyChanged("MenuType");
					this.OnMenuTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuHide", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> MenuHide
		{
			get
			{
				return this._MenuHide;
			}
			set
			{
				if ((this._MenuHide != value))
				{
					this.OnMenuHideChanging(value);
					this.SendPropertyChanging();
					this._MenuHide = value;
					this.SendPropertyChanged("MenuHide");
					this.OnMenuHideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmsOn", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> SmsOn
		{
			get
			{
				return this._SmsOn;
			}
			set
			{
				if ((this._SmsOn != value))
				{
					this.OnSmsOnChanging(value);
					this.SendPropertyChanging();
					this._SmsOn = value;
					this.SendPropertyChanged("SmsOn");
					this.OnSmsOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallSound", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> CallSound
		{
			get
			{
				return this._CallSound;
			}
			set
			{
				if ((this._CallSound != value))
				{
					this.OnCallSoundChanging(value);
					this.SendPropertyChanging();
					this._CallSound = value;
					this.SendPropertyChanged("CallSound");
					this.OnCallSoundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Theme", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Theme
		{
			get
			{
				return this._Theme;
			}
			set
			{
				if ((this._Theme != value))
				{
					this.OnThemeChanging(value);
					this.SendPropertyChanging();
					this._Theme = value;
					this.SendPropertyChanged("Theme");
					this.OnThemeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MytableLeft", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string MytableLeft
		{
			get
			{
				return this._MytableLeft;
			}
			set
			{
				if ((this._MytableLeft != value))
				{
					this.OnMytableLeftChanging(value);
					this.SendPropertyChanging();
					this._MytableLeft = value;
					this.SendPropertyChanged("MytableLeft");
					this.OnMytableLeftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MytableRight", DbType="NVarChar(200)", UpdateCheck=UpdateCheck.Never)]
		public string MytableRight
		{
			get
			{
				return this._MytableRight;
			}
			set
			{
				if ((this._MytableRight != value))
				{
					this.OnMytableRightChanging(value);
					this.SendPropertyChanging();
					this._MytableRight = value;
					this.SendPropertyChanged("MytableRight");
					this.OnMytableRightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailCapacity", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> EmailCapacity
		{
			get
			{
				return this._EmailCapacity;
			}
			set
			{
				if ((this._EmailCapacity != value))
				{
					this.OnEmailCapacityChanging(value);
					this.SendPropertyChanging();
					this._EmailCapacity = value;
					this.SendPropertyChanged("EmailCapacity");
					this.OnEmailCapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolderCapacity", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> FolderCapacity
		{
			get
			{
				return this._FolderCapacity;
			}
			set
			{
				if ((this._FolderCapacity != value))
				{
					this.OnFolderCapacityChanging(value);
					this.SendPropertyChanging();
					this._FolderCapacity = value;
					this.SendPropertyChanged("FolderCapacity");
					this.OnFolderCapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnlineTime", DbType="Real", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<float> OnlineTime
		{
			get
			{
				return this._OnlineTime;
			}
			set
			{
				if ((this._OnlineTime != value))
				{
					this.OnOnlineTimeChanging(value);
					this.SendPropertyChanging();
					this._OnlineTime = value;
					this.SendPropertyChanged("OnlineTime");
					this.OnOnlineTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DutyType", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> DutyType
		{
			get
			{
				return this._DutyType;
			}
			set
			{
				if ((this._DutyType != value))
				{
					this.OnDutyTypeChanging(value);
					this.SendPropertyChanging();
					this._DutyType = value;
					this.SendPropertyChanged("DutyType");
					this.OnDutyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendCard", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string AttendCard
		{
			get
			{
				return this._AttendCard;
			}
			set
			{
				if ((this._AttendCard != value))
				{
					this.OnAttendCardChanging(value);
					this.SendPropertyChanging();
					this._AttendCard = value;
					this.SendPropertyChanged("AttendCard");
					this.OnAttendCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPassTime", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime LastPassTime
		{
			get
			{
				return this._LastPassTime;
			}
			set
			{
				if ((this._LastPassTime != value))
				{
					this.OnLastPassTimeChanging(value);
					this.SendPropertyChanging();
					this._LastPassTime = value;
					this.SendPropertyChanged("LastPassTime");
					this.OnLastPassTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastVisitTime", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime LastVisitTime
		{
			get
			{
				return this._LastVisitTime;
			}
			set
			{
				if ((this._LastVisitTime != value))
				{
					this.OnLastVisitTimeChanging(value);
					this.SendPropertyChanging();
					this._LastVisitTime = value;
					this.SendPropertyChanged("LastVisitTime");
					this.OnLastVisitTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastIp", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string LastIp
		{
			get
			{
				return this._LastIp;
			}
			set
			{
				if ((this._LastIp != value))
				{
					this.OnLastIpChanging(value);
					this.SendPropertyChanging();
					this._LastIp = value;
					this.SendPropertyChanged("LastIp");
					this.OnLastIpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disabled", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Disabled
		{
			get
			{
				return this._Disabled;
			}
			set
			{
				if ((this._Disabled != value))
				{
					this.OnDisabledChanging(value);
					this.SendPropertyChanging();
					this._Disabled = value;
					this.SendPropertyChanged("Disabled");
					this.OnDisabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BindIp", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string BindIp
		{
			get
			{
				return this._BindIp;
			}
			set
			{
				if ((this._BindIp != value))
				{
					this.OnBindIpChanging(value);
					this.SendPropertyChanging();
					this._BindIp = value;
					this.SendPropertyChanged("BindIp");
					this.OnBindIpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsingKey", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> UsingKey
		{
			get
			{
				return this._UsingKey;
			}
			set
			{
				if ((this._UsingKey != value))
				{
					this.OnUsingKeyChanging(value);
					this.SendPropertyChanging();
					this._UsingKey = value;
					this.SendPropertyChanged("UsingKey");
					this.OnUsingKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UGuid", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string UGuid
		{
			get
			{
				return this._UGuid;
			}
			set
			{
				if ((this._UGuid != value))
				{
					this.OnUGuidChanging(value);
					this.SendPropertyChanging();
					this._UGuid = value;
					this.SendPropertyChanged("UGuid");
					this.OnUGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UKey", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string UKey
		{
			get
			{
				return this._UKey;
			}
			set
			{
				if ((this._UKey != value))
				{
					this.OnUKeyChanging(value);
					this.SendPropertyChanging();
					this._UKey = value;
					this.SendPropertyChanged("UKey");
					this.OnUKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UExt", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string UExt
		{
			get
			{
				return this._UExt;
			}
			set
			{
				if ((this._UExt != value))
				{
					this.OnUExtChanging(value);
					this.SendPropertyChanging();
					this._UExt = value;
					this.SendPropertyChanged("UExt");
					this.OnUExtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotUser", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> NotUser
		{
			get
			{
				return this._NotUser;
			}
			set
			{
				if ((this._NotUser != value))
				{
					this.OnNotUserChanging(value);
					this.SendPropertyChanging();
					this._NotUser = value;
					this.SendPropertyChanged("NotUser");
					this.OnNotUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotTable", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> NotTable
		{
			get
			{
				return this._NotTable;
			}
			set
			{
				if ((this._NotTable != value))
				{
					this.OnNotTableChanging(value);
					this.SendPropertyChanging();
					this._NotTable = value;
					this.SendPropertyChanged("NotTable");
					this.OnNotTableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultMenu", DbType="NVarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string DefaultMenu
		{
			get
			{
				return this._DefaultMenu;
			}
			set
			{
				if ((this._DefaultMenu != value))
				{
					this.OnDefaultMenuChanging(value);
					this.SendPropertyChanging();
					this._DefaultMenu = value;
					this.SendPropertyChanged("DefaultMenu");
					this.OnDefaultMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TablePhoto", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string TablePhoto
		{
			get
			{
				return this._TablePhoto;
			}
			set
			{
				if ((this._TablePhoto != value))
				{
					this.OnTablePhotoChanging(value);
					this.SendPropertyChanging();
					this._TablePhoto = value;
					this.SendPropertyChanged("TablePhoto");
					this.OnTablePhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebmailNum", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> WebmailNum
		{
			get
			{
				return this._WebmailNum;
			}
			set
			{
				if ((this._WebmailNum != value))
				{
					this.OnWebmailNumChanging(value);
					this.SendPropertyChanging();
					this._WebmailNum = value;
					this.SendPropertyChanged("WebmailNum");
					this.OnWebmailNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebmailCapacity", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> WebmailCapacity
		{
			get
			{
				return this._WebmailCapacity;
			}
			set
			{
				if ((this._WebmailCapacity != value))
				{
					this.OnWebmailCapacityChanging(value);
					this.SendPropertyChanging();
					this._WebmailCapacity = value;
					this.SendPropertyChanged("WebmailCapacity");
					this.OnWebmailCapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdUserId", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string AdUserId
		{
			get
			{
				return this._AdUserId;
			}
			set
			{
				if ((this._AdUserId != value))
				{
					this.OnAdUserIdChanging(value);
					this.SendPropertyChanging();
					this._AdUserId = value;
					this.SendPropertyChanged("AdUserId");
					this.OnAdUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsingAd", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> UsingAd
		{
			get
			{
				return this._UsingAd;
			}
			set
			{
				if ((this._UsingAd != value))
				{
					this.OnUsingAdChanging(value);
					this.SendPropertyChanging();
					this._UsingAd = value;
					this.SendPropertyChanged("UsingAd");
					this.OnUsingAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModify", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary LastModify
		{
			get
			{
				return this._LastModify;
			}
			set
			{
				if ((this._LastModify != value))
				{
					this.OnLastModifyChanging(value);
					this.SendPropertyChanging();
					this._LastModify = value;
					this.SendPropertyChanged("LastModify");
					this.OnLastModifyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPosId", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> UserPosId
		{
			get
			{
				return this._UserPosId;
			}
			set
			{
				if ((this._UserPosId != value))
				{
					this.OnUserPosIdChanging(value);
					this.SendPropertyChanging();
					this._UserPosId = value;
					this.SendPropertyChanged("UserPosId");
					this.OnUserPosIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userrole", DbType="VarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string userrole
		{
			get
			{
				return this._userrole;
			}
			set
			{
				if ((this._userrole != value))
				{
					this.OnuserroleChanging(value);
					this.SendPropertyChanging();
					this._userrole = value;
					this.SendPropertyChanged("userrole");
					this.OnuserroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOBJID", DbType="Char(8)", UpdateCheck=UpdateCheck.Never)]
		public string SOBJID
		{
			get
			{
				return this._SOBJID;
			}
			set
			{
				if ((this._SOBJID != value))
				{
					this.OnSOBJIDChanging(value);
					this.SendPropertyChanging();
					this._SOBJID = value;
					this.SendPropertyChanged("SOBJID");
					this.OnSOBJIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAT2", DbType="Char(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<char> STAT2
		{
			get
			{
				return this._STAT2;
			}
			set
			{
				if ((this._STAT2 != value))
				{
					this.OnSTAT2Changing(value);
					this.SendPropertyChanging();
					this._STAT2 = value;
					this.SendPropertyChanged("STAT2");
					this.OnSTAT2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISTAT", DbType="Char(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<char> ISTAT
		{
			get
			{
				return this._ISTAT;
			}
			set
			{
				if ((this._ISTAT != value))
				{
					this.OnISTATChanging(value);
					this.SendPropertyChanging();
					this._ISTAT = value;
					this.SendPropertyChanged("ISTAT");
					this.OnISTATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOSTL", DbType="Char(10)", UpdateCheck=UpdateCheck.Never)]
		public string KOSTL
		{
			get
			{
				return this._KOSTL;
			}
			set
			{
				if ((this._KOSTL != value))
				{
					this.OnKOSTLChanging(value);
					this.SendPropertyChanging();
					this._KOSTL = value;
					this.SendPropertyChanged("KOSTL");
					this.OnKOSTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUKRS", DbType="Char(4)", UpdateCheck=UpdateCheck.Never)]
		public string BUKRS
		{
			get
			{
				return this._BUKRS;
			}
			set
			{
				if ((this._BUKRS != value))
				{
					this.OnBUKRSChanging(value);
					this.SendPropertyChanging();
					this._BUKRS = value;
					this.SendPropertyChanged("BUKRS");
					this.OnBUKRSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WERKS", DbType="Char(4)", UpdateCheck=UpdateCheck.Never)]
		public string WERKS
		{
			get
			{
				return this._WERKS;
			}
			set
			{
				if ((this._WERKS != value))
				{
					this.OnWERKSChanging(value);
					this.SendPropertyChanging();
					this._WERKS = value;
					this.SendPropertyChanged("WERKS");
					this.OnWERKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERSG", DbType="Char(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<char> PERSG
		{
			get
			{
				return this._PERSG;
			}
			set
			{
				if ((this._PERSG != value))
				{
					this.OnPERSGChanging(value);
					this.SendPropertyChanging();
					this._PERSG = value;
					this.SendPropertyChanged("PERSG");
					this.OnPERSGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERSK", DbType="Char(2)", UpdateCheck=UpdateCheck.Never)]
		public string PERSK
		{
			get
			{
				return this._PERSK;
			}
			set
			{
				if ((this._PERSK != value))
				{
					this.OnPERSKChanging(value);
					this.SendPropertyChanging();
					this._PERSK = value;
					this.SendPropertyChanged("PERSK");
					this.OnPERSKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VDSK1", DbType="Char(14)", UpdateCheck=UpdateCheck.Never)]
		public string VDSK1
		{
			get
			{
				return this._VDSK1;
			}
			set
			{
				if ((this._VDSK1 != value))
				{
					this.OnVDSK1Changing(value);
					this.SendPropertyChanging();
					this._VDSK1 = value;
					this.SendPropertyChanged("VDSK1");
					this.OnVDSK1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GSBER", DbType="Char(4)", UpdateCheck=UpdateCheck.Never)]
		public string GSBER
		{
			get
			{
				return this._GSBER;
			}
			set
			{
				if ((this._GSBER != value))
				{
					this.OnGSBERChanging(value);
					this.SendPropertyChanging();
					this._GSBER = value;
					this.SendPropertyChanged("GSBER");
					this.OnGSBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BTRTL", DbType="Char(4)", UpdateCheck=UpdateCheck.Never)]
		public string BTRTL
		{
			get
			{
				return this._BTRTL;
			}
			set
			{
				if ((this._BTRTL != value))
				{
					this.OnBTRTLChanging(value);
					this.SendPropertyChanging();
					this._BTRTL = value;
					this.SendPropertyChanged("BTRTL");
					this.OnBTRTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABKRS", DbType="Char(2)", UpdateCheck=UpdateCheck.Never)]
		public string ABKRS
		{
			get
			{
				return this._ABKRS;
			}
			set
			{
				if ((this._ABKRS != value))
				{
					this.OnABKRSChanging(value);
					this.SendPropertyChanging();
					this._ABKRS = value;
					this.SendPropertyChanged("ABKRS");
					this.OnABKRSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STELL", DbType="Char(8)", UpdateCheck=UpdateCheck.Never)]
		public string STELL
		{
			get
			{
				return this._STELL;
			}
			set
			{
				if ((this._STELL != value))
				{
					this.OnSTELLChanging(value);
					this.SendPropertyChanging();
					this._STELL = value;
					this.SendPropertyChanged("STELL");
					this.OnSTELLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBMOD", DbType="Char(4)", UpdateCheck=UpdateCheck.Never)]
		public string SBMOD
		{
			get
			{
				return this._SBMOD;
			}
			set
			{
				if ((this._SBMOD != value))
				{
					this.OnSBMODChanging(value);
					this.SendPropertyChanging();
					this._SBMOD = value;
					this.SendPropertyChanged("SBMOD");
					this.OnSBMODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ICNUM", DbType="NVarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string ICNUM
		{
			get
			{
				return this._ICNUM;
			}
			set
			{
				if ((this._ICNUM != value))
				{
					this.OnICNUMChanging(value);
					this.SendPropertyChanging();
					this._ICNUM = value;
					this.SendPropertyChanged("ICNUM");
					this.OnICNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERCARD", DbType="NVarChar(30)", UpdateCheck=UpdateCheck.Never)]
		public string USERCARD
		{
			get
			{
				return this._USERCARD;
			}
			set
			{
				if ((this._USERCARD != value))
				{
					this.OnUSERCARDChanging(value);
					this.SendPropertyChanging();
					this._USERCARD = value;
					this.SendPropertyChanged("USERCARD");
					this.OnUSERCARDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
