<?xml version="1.0" encoding="utf-8"?><Database Name="HXWebAPPDB" Class="HXWebDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.0.51.206;Initial Catalog=HXWebAPPDB;Persist Security Info=True;User ID=sa" SettingsObjectName="DLL.Properties.Settings" SettingsPropertyName="HXWebAPPDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.M_MENU_INFO" Member="M_MENU_INFO">
    <Type Name="M_MENU_INFO">
      <Column Name="MENU_ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MENU_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MENU_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MENU_URL" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CODEID_FOR_MENULEVEL" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MENU_UPMENU" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CODEID_FOR_MENUSTATUS" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MENU_CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MENU_CREATEUSER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MENU_LASTUPDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MENU_LASTUPDATEUSER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MENU_COL1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MENU_COL2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MENU_COL3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_ROLE_MENUS" Member="M_ROLE_MENUS">
    <Type Name="M_ROLE_MENUS">
      <Column Name="RMID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ROLE_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MENU_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RM_CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RM_CREATEUSER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RM_LASTUPDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RM_LASTUPDATEUSER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RM_COL1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RM_COL2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RM_COL3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_ROLES" Member="M_ROLES">
    <Type Name="M_ROLES">
      <Column Name="ROLE_ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ROLE_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ROLE_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CODEID_FOR_ROLESTATUS" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ROLE_CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ROLE_CREATEUSER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ROLE_LASTUPDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ROLE_LASTUPDATEUSER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ROLE_COL1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ROLE_COL2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ROLE_COL3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_USER_ROLES" Member="M_USER_ROLES">
    <Type Name="M_USER_ROLES">
      <Column Name="URID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USERID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ROLE_CODE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UR_CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UR_CREATEUSER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UR_LASTUPDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UR_LASTUPDATEUSER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UR_COL1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UR_COL2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UR_COL3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.M_SYS_INFO" Member="M_SYS_INFO">
    <Type Name="M_SYS_INFO">
      <Column Name="SYS_ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SYS_VSERION" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SYS_UPDATE_CONTENT" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SYS_UPDATE_TIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CODEID_FOR_SYSTYPE" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SYS_CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SYS_CREATEUSER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SYS_LASTUPDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SYS_LASTUPDATEUSER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SYS_COL1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SYS_COL2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SYS_COL3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>