#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HXWebAPPDB")]
	public partial class HXWebDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertM_MENU_INFO(M_MENU_INFO instance);
    partial void UpdateM_MENU_INFO(M_MENU_INFO instance);
    partial void DeleteM_MENU_INFO(M_MENU_INFO instance);
    partial void InsertM_ROLE_MENUS(M_ROLE_MENUS instance);
    partial void UpdateM_ROLE_MENUS(M_ROLE_MENUS instance);
    partial void DeleteM_ROLE_MENUS(M_ROLE_MENUS instance);
    partial void InsertM_ROLES(M_ROLES instance);
    partial void UpdateM_ROLES(M_ROLES instance);
    partial void DeleteM_ROLES(M_ROLES instance);
    partial void InsertM_USER_ROLES(M_USER_ROLES instance);
    partial void UpdateM_USER_ROLES(M_USER_ROLES instance);
    partial void DeleteM_USER_ROLES(M_USER_ROLES instance);
    partial void InsertM_SYS_INFO(M_SYS_INFO instance);
    partial void UpdateM_SYS_INFO(M_SYS_INFO instance);
    partial void DeleteM_SYS_INFO(M_SYS_INFO instance);
    #endregion
		
		public HXWebDBDataContext() : 
				base(global::DLL.Properties.Settings.Default.HXWebAPPDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HXWebDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HXWebDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HXWebDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HXWebDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<M_MENU_INFO> M_MENU_INFO
		{
			get
			{
				return this.GetTable<M_MENU_INFO>();
			}
		}
		
		public System.Data.Linq.Table<M_ROLE_MENUS> M_ROLE_MENUS
		{
			get
			{
				return this.GetTable<M_ROLE_MENUS>();
			}
		}
		
		public System.Data.Linq.Table<M_ROLES> M_ROLES
		{
			get
			{
				return this.GetTable<M_ROLES>();
			}
		}
		
		public System.Data.Linq.Table<M_USER_ROLES> M_USER_ROLES
		{
			get
			{
				return this.GetTable<M_USER_ROLES>();
			}
		}
		
		public System.Data.Linq.Table<M_SYS_INFO> M_SYS_INFO
		{
			get
			{
				return this.GetTable<M_SYS_INFO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_MENU_INFO")]
	public partial class M_MENU_INFO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MENU_ID;
		
		private string _MENU_CODE;
		
		private string _MENU_NAME;
		
		private string _MENU_URL;
		
		private string _CODEID_FOR_MENULEVEL;
		
		private string _MENU_UPMENU;
		
		private string _CODEID_FOR_MENUSTATUS;
		
		private System.Nullable<System.DateTime> _MENU_CREATE_DATE;
		
		private string _MENU_CREATEUSER;
		
		private System.Nullable<System.DateTime> _MENU_LASTUPDATE;
		
		private string _MENU_LASTUPDATEUSER;
		
		private string _MENU_COL1;
		
		private string _MENU_COL2;
		
		private string _MENU_COL3;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMENU_IDChanging(long value);
    partial void OnMENU_IDChanged();
    partial void OnMENU_CODEChanging(string value);
    partial void OnMENU_CODEChanged();
    partial void OnMENU_NAMEChanging(string value);
    partial void OnMENU_NAMEChanged();
    partial void OnMENU_URLChanging(string value);
    partial void OnMENU_URLChanged();
    partial void OnCODEID_FOR_MENULEVELChanging(string value);
    partial void OnCODEID_FOR_MENULEVELChanged();
    partial void OnMENU_UPMENUChanging(string value);
    partial void OnMENU_UPMENUChanged();
    partial void OnCODEID_FOR_MENUSTATUSChanging(string value);
    partial void OnCODEID_FOR_MENUSTATUSChanged();
    partial void OnMENU_CREATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMENU_CREATE_DATEChanged();
    partial void OnMENU_CREATEUSERChanging(string value);
    partial void OnMENU_CREATEUSERChanged();
    partial void OnMENU_LASTUPDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMENU_LASTUPDATEChanged();
    partial void OnMENU_LASTUPDATEUSERChanging(string value);
    partial void OnMENU_LASTUPDATEUSERChanged();
    partial void OnMENU_COL1Changing(string value);
    partial void OnMENU_COL1Changed();
    partial void OnMENU_COL2Changing(string value);
    partial void OnMENU_COL2Changed();
    partial void OnMENU_COL3Changing(string value);
    partial void OnMENU_COL3Changed();
    #endregion
		
		public M_MENU_INFO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MENU_ID
		{
			get
			{
				return this._MENU_ID;
			}
			set
			{
				if ((this._MENU_ID != value))
				{
					this.OnMENU_IDChanging(value);
					this.SendPropertyChanging();
					this._MENU_ID = value;
					this.SendPropertyChanged("MENU_ID");
					this.OnMENU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MENU_CODE
		{
			get
			{
				return this._MENU_CODE;
			}
			set
			{
				if ((this._MENU_CODE != value))
				{
					this.OnMENU_CODEChanging(value);
					this.SendPropertyChanging();
					this._MENU_CODE = value;
					this.SendPropertyChanged("MENU_CODE");
					this.OnMENU_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MENU_NAME
		{
			get
			{
				return this._MENU_NAME;
			}
			set
			{
				if ((this._MENU_NAME != value))
				{
					this.OnMENU_NAMEChanging(value);
					this.SendPropertyChanging();
					this._MENU_NAME = value;
					this.SendPropertyChanged("MENU_NAME");
					this.OnMENU_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_URL", DbType="NVarChar(150)")]
		public string MENU_URL
		{
			get
			{
				return this._MENU_URL;
			}
			set
			{
				if ((this._MENU_URL != value))
				{
					this.OnMENU_URLChanging(value);
					this.SendPropertyChanging();
					this._MENU_URL = value;
					this.SendPropertyChanged("MENU_URL");
					this.OnMENU_URLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODEID_FOR_MENULEVEL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CODEID_FOR_MENULEVEL
		{
			get
			{
				return this._CODEID_FOR_MENULEVEL;
			}
			set
			{
				if ((this._CODEID_FOR_MENULEVEL != value))
				{
					this.OnCODEID_FOR_MENULEVELChanging(value);
					this.SendPropertyChanging();
					this._CODEID_FOR_MENULEVEL = value;
					this.SendPropertyChanged("CODEID_FOR_MENULEVEL");
					this.OnCODEID_FOR_MENULEVELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_UPMENU", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MENU_UPMENU
		{
			get
			{
				return this._MENU_UPMENU;
			}
			set
			{
				if ((this._MENU_UPMENU != value))
				{
					this.OnMENU_UPMENUChanging(value);
					this.SendPropertyChanging();
					this._MENU_UPMENU = value;
					this.SendPropertyChanged("MENU_UPMENU");
					this.OnMENU_UPMENUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODEID_FOR_MENUSTATUS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CODEID_FOR_MENUSTATUS
		{
			get
			{
				return this._CODEID_FOR_MENUSTATUS;
			}
			set
			{
				if ((this._CODEID_FOR_MENUSTATUS != value))
				{
					this.OnCODEID_FOR_MENUSTATUSChanging(value);
					this.SendPropertyChanging();
					this._CODEID_FOR_MENUSTATUS = value;
					this.SendPropertyChanged("CODEID_FOR_MENUSTATUS");
					this.OnCODEID_FOR_MENUSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_CREATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MENU_CREATE_DATE
		{
			get
			{
				return this._MENU_CREATE_DATE;
			}
			set
			{
				if ((this._MENU_CREATE_DATE != value))
				{
					this.OnMENU_CREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._MENU_CREATE_DATE = value;
					this.SendPropertyChanged("MENU_CREATE_DATE");
					this.OnMENU_CREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_CREATEUSER", DbType="NVarChar(50)")]
		public string MENU_CREATEUSER
		{
			get
			{
				return this._MENU_CREATEUSER;
			}
			set
			{
				if ((this._MENU_CREATEUSER != value))
				{
					this.OnMENU_CREATEUSERChanging(value);
					this.SendPropertyChanging();
					this._MENU_CREATEUSER = value;
					this.SendPropertyChanged("MENU_CREATEUSER");
					this.OnMENU_CREATEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_LASTUPDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MENU_LASTUPDATE
		{
			get
			{
				return this._MENU_LASTUPDATE;
			}
			set
			{
				if ((this._MENU_LASTUPDATE != value))
				{
					this.OnMENU_LASTUPDATEChanging(value);
					this.SendPropertyChanging();
					this._MENU_LASTUPDATE = value;
					this.SendPropertyChanged("MENU_LASTUPDATE");
					this.OnMENU_LASTUPDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_LASTUPDATEUSER", DbType="NVarChar(50)")]
		public string MENU_LASTUPDATEUSER
		{
			get
			{
				return this._MENU_LASTUPDATEUSER;
			}
			set
			{
				if ((this._MENU_LASTUPDATEUSER != value))
				{
					this.OnMENU_LASTUPDATEUSERChanging(value);
					this.SendPropertyChanging();
					this._MENU_LASTUPDATEUSER = value;
					this.SendPropertyChanged("MENU_LASTUPDATEUSER");
					this.OnMENU_LASTUPDATEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_COL1", DbType="NVarChar(50)")]
		public string MENU_COL1
		{
			get
			{
				return this._MENU_COL1;
			}
			set
			{
				if ((this._MENU_COL1 != value))
				{
					this.OnMENU_COL1Changing(value);
					this.SendPropertyChanging();
					this._MENU_COL1 = value;
					this.SendPropertyChanged("MENU_COL1");
					this.OnMENU_COL1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_COL2", DbType="NVarChar(50)")]
		public string MENU_COL2
		{
			get
			{
				return this._MENU_COL2;
			}
			set
			{
				if ((this._MENU_COL2 != value))
				{
					this.OnMENU_COL2Changing(value);
					this.SendPropertyChanging();
					this._MENU_COL2 = value;
					this.SendPropertyChanged("MENU_COL2");
					this.OnMENU_COL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_COL3", DbType="NVarChar(50)")]
		public string MENU_COL3
		{
			get
			{
				return this._MENU_COL3;
			}
			set
			{
				if ((this._MENU_COL3 != value))
				{
					this.OnMENU_COL3Changing(value);
					this.SendPropertyChanging();
					this._MENU_COL3 = value;
					this.SendPropertyChanged("MENU_COL3");
					this.OnMENU_COL3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_ROLE_MENUS")]
	public partial class M_ROLE_MENUS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _RMID;
		
		private string _ROLE_CODE;
		
		private string _MENU_CODE;
		
		private System.Nullable<System.DateTime> _RM_CREATE_DATE;
		
		private string _RM_CREATEUSER;
		
		private System.Nullable<System.DateTime> _RM_LASTUPDATE;
		
		private string _RM_LASTUPDATEUSER;
		
		private string _RM_COL1;
		
		private string _RM_COL2;
		
		private string _RM_COL3;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRMIDChanging(long value);
    partial void OnRMIDChanged();
    partial void OnROLE_CODEChanging(string value);
    partial void OnROLE_CODEChanged();
    partial void OnMENU_CODEChanging(string value);
    partial void OnMENU_CODEChanged();
    partial void OnRM_CREATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnRM_CREATE_DATEChanged();
    partial void OnRM_CREATEUSERChanging(string value);
    partial void OnRM_CREATEUSERChanged();
    partial void OnRM_LASTUPDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnRM_LASTUPDATEChanged();
    partial void OnRM_LASTUPDATEUSERChanging(string value);
    partial void OnRM_LASTUPDATEUSERChanged();
    partial void OnRM_COL1Changing(string value);
    partial void OnRM_COL1Changed();
    partial void OnRM_COL2Changing(string value);
    partial void OnRM_COL2Changed();
    partial void OnRM_COL3Changing(string value);
    partial void OnRM_COL3Changed();
    #endregion
		
		public M_ROLE_MENUS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long RMID
		{
			get
			{
				return this._RMID;
			}
			set
			{
				if ((this._RMID != value))
				{
					this.OnRMIDChanging(value);
					this.SendPropertyChanging();
					this._RMID = value;
					this.SendPropertyChanged("RMID");
					this.OnRMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ROLE_CODE
		{
			get
			{
				return this._ROLE_CODE;
			}
			set
			{
				if ((this._ROLE_CODE != value))
				{
					this.OnROLE_CODEChanging(value);
					this.SendPropertyChanging();
					this._ROLE_CODE = value;
					this.SendPropertyChanged("ROLE_CODE");
					this.OnROLE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MENU_CODE
		{
			get
			{
				return this._MENU_CODE;
			}
			set
			{
				if ((this._MENU_CODE != value))
				{
					this.OnMENU_CODEChanging(value);
					this.SendPropertyChanging();
					this._MENU_CODE = value;
					this.SendPropertyChanged("MENU_CODE");
					this.OnMENU_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RM_CREATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> RM_CREATE_DATE
		{
			get
			{
				return this._RM_CREATE_DATE;
			}
			set
			{
				if ((this._RM_CREATE_DATE != value))
				{
					this.OnRM_CREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._RM_CREATE_DATE = value;
					this.SendPropertyChanged("RM_CREATE_DATE");
					this.OnRM_CREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RM_CREATEUSER", DbType="NVarChar(50)")]
		public string RM_CREATEUSER
		{
			get
			{
				return this._RM_CREATEUSER;
			}
			set
			{
				if ((this._RM_CREATEUSER != value))
				{
					this.OnRM_CREATEUSERChanging(value);
					this.SendPropertyChanging();
					this._RM_CREATEUSER = value;
					this.SendPropertyChanged("RM_CREATEUSER");
					this.OnRM_CREATEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RM_LASTUPDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> RM_LASTUPDATE
		{
			get
			{
				return this._RM_LASTUPDATE;
			}
			set
			{
				if ((this._RM_LASTUPDATE != value))
				{
					this.OnRM_LASTUPDATEChanging(value);
					this.SendPropertyChanging();
					this._RM_LASTUPDATE = value;
					this.SendPropertyChanged("RM_LASTUPDATE");
					this.OnRM_LASTUPDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RM_LASTUPDATEUSER", DbType="NVarChar(50)")]
		public string RM_LASTUPDATEUSER
		{
			get
			{
				return this._RM_LASTUPDATEUSER;
			}
			set
			{
				if ((this._RM_LASTUPDATEUSER != value))
				{
					this.OnRM_LASTUPDATEUSERChanging(value);
					this.SendPropertyChanging();
					this._RM_LASTUPDATEUSER = value;
					this.SendPropertyChanged("RM_LASTUPDATEUSER");
					this.OnRM_LASTUPDATEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RM_COL1", DbType="NVarChar(50)")]
		public string RM_COL1
		{
			get
			{
				return this._RM_COL1;
			}
			set
			{
				if ((this._RM_COL1 != value))
				{
					this.OnRM_COL1Changing(value);
					this.SendPropertyChanging();
					this._RM_COL1 = value;
					this.SendPropertyChanged("RM_COL1");
					this.OnRM_COL1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RM_COL2", DbType="NVarChar(50)")]
		public string RM_COL2
		{
			get
			{
				return this._RM_COL2;
			}
			set
			{
				if ((this._RM_COL2 != value))
				{
					this.OnRM_COL2Changing(value);
					this.SendPropertyChanging();
					this._RM_COL2 = value;
					this.SendPropertyChanged("RM_COL2");
					this.OnRM_COL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RM_COL3", DbType="NVarChar(50)")]
		public string RM_COL3
		{
			get
			{
				return this._RM_COL3;
			}
			set
			{
				if ((this._RM_COL3 != value))
				{
					this.OnRM_COL3Changing(value);
					this.SendPropertyChanging();
					this._RM_COL3 = value;
					this.SendPropertyChanged("RM_COL3");
					this.OnRM_COL3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_ROLES")]
	public partial class M_ROLES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ROLE_ID;
		
		private string _ROLE_CODE;
		
		private string _ROLE_NAME;
		
		private string _CODEID_FOR_ROLESTATUS;
		
		private System.Nullable<System.DateTime> _ROLE_CREATE_DATE;
		
		private string _ROLE_CREATEUSER;
		
		private System.Nullable<System.DateTime> _ROLE_LASTUPDATE;
		
		private string _ROLE_LASTUPDATEUSER;
		
		private string _ROLE_COL1;
		
		private string _ROLE_COL2;
		
		private string _ROLE_COL3;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnROLE_IDChanging(long value);
    partial void OnROLE_IDChanged();
    partial void OnROLE_CODEChanging(string value);
    partial void OnROLE_CODEChanged();
    partial void OnROLE_NAMEChanging(string value);
    partial void OnROLE_NAMEChanged();
    partial void OnCODEID_FOR_ROLESTATUSChanging(string value);
    partial void OnCODEID_FOR_ROLESTATUSChanged();
    partial void OnROLE_CREATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnROLE_CREATE_DATEChanged();
    partial void OnROLE_CREATEUSERChanging(string value);
    partial void OnROLE_CREATEUSERChanged();
    partial void OnROLE_LASTUPDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnROLE_LASTUPDATEChanged();
    partial void OnROLE_LASTUPDATEUSERChanging(string value);
    partial void OnROLE_LASTUPDATEUSERChanged();
    partial void OnROLE_COL1Changing(string value);
    partial void OnROLE_COL1Changed();
    partial void OnROLE_COL2Changing(string value);
    partial void OnROLE_COL2Changed();
    partial void OnROLE_COL3Changing(string value);
    partial void OnROLE_COL3Changed();
    #endregion
		
		public M_ROLES()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ROLE_ID
		{
			get
			{
				return this._ROLE_ID;
			}
			set
			{
				if ((this._ROLE_ID != value))
				{
					this.OnROLE_IDChanging(value);
					this.SendPropertyChanging();
					this._ROLE_ID = value;
					this.SendPropertyChanged("ROLE_ID");
					this.OnROLE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ROLE_CODE
		{
			get
			{
				return this._ROLE_CODE;
			}
			set
			{
				if ((this._ROLE_CODE != value))
				{
					this.OnROLE_CODEChanging(value);
					this.SendPropertyChanging();
					this._ROLE_CODE = value;
					this.SendPropertyChanged("ROLE_CODE");
					this.OnROLE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ROLE_NAME
		{
			get
			{
				return this._ROLE_NAME;
			}
			set
			{
				if ((this._ROLE_NAME != value))
				{
					this.OnROLE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._ROLE_NAME = value;
					this.SendPropertyChanged("ROLE_NAME");
					this.OnROLE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODEID_FOR_ROLESTATUS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CODEID_FOR_ROLESTATUS
		{
			get
			{
				return this._CODEID_FOR_ROLESTATUS;
			}
			set
			{
				if ((this._CODEID_FOR_ROLESTATUS != value))
				{
					this.OnCODEID_FOR_ROLESTATUSChanging(value);
					this.SendPropertyChanging();
					this._CODEID_FOR_ROLESTATUS = value;
					this.SendPropertyChanged("CODEID_FOR_ROLESTATUS");
					this.OnCODEID_FOR_ROLESTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_CREATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> ROLE_CREATE_DATE
		{
			get
			{
				return this._ROLE_CREATE_DATE;
			}
			set
			{
				if ((this._ROLE_CREATE_DATE != value))
				{
					this.OnROLE_CREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._ROLE_CREATE_DATE = value;
					this.SendPropertyChanged("ROLE_CREATE_DATE");
					this.OnROLE_CREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_CREATEUSER", DbType="NVarChar(50)")]
		public string ROLE_CREATEUSER
		{
			get
			{
				return this._ROLE_CREATEUSER;
			}
			set
			{
				if ((this._ROLE_CREATEUSER != value))
				{
					this.OnROLE_CREATEUSERChanging(value);
					this.SendPropertyChanging();
					this._ROLE_CREATEUSER = value;
					this.SendPropertyChanged("ROLE_CREATEUSER");
					this.OnROLE_CREATEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_LASTUPDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> ROLE_LASTUPDATE
		{
			get
			{
				return this._ROLE_LASTUPDATE;
			}
			set
			{
				if ((this._ROLE_LASTUPDATE != value))
				{
					this.OnROLE_LASTUPDATEChanging(value);
					this.SendPropertyChanging();
					this._ROLE_LASTUPDATE = value;
					this.SendPropertyChanged("ROLE_LASTUPDATE");
					this.OnROLE_LASTUPDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_LASTUPDATEUSER", DbType="NVarChar(50)")]
		public string ROLE_LASTUPDATEUSER
		{
			get
			{
				return this._ROLE_LASTUPDATEUSER;
			}
			set
			{
				if ((this._ROLE_LASTUPDATEUSER != value))
				{
					this.OnROLE_LASTUPDATEUSERChanging(value);
					this.SendPropertyChanging();
					this._ROLE_LASTUPDATEUSER = value;
					this.SendPropertyChanged("ROLE_LASTUPDATEUSER");
					this.OnROLE_LASTUPDATEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_COL1", DbType="NVarChar(50)")]
		public string ROLE_COL1
		{
			get
			{
				return this._ROLE_COL1;
			}
			set
			{
				if ((this._ROLE_COL1 != value))
				{
					this.OnROLE_COL1Changing(value);
					this.SendPropertyChanging();
					this._ROLE_COL1 = value;
					this.SendPropertyChanged("ROLE_COL1");
					this.OnROLE_COL1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_COL2", DbType="NVarChar(50)")]
		public string ROLE_COL2
		{
			get
			{
				return this._ROLE_COL2;
			}
			set
			{
				if ((this._ROLE_COL2 != value))
				{
					this.OnROLE_COL2Changing(value);
					this.SendPropertyChanging();
					this._ROLE_COL2 = value;
					this.SendPropertyChanged("ROLE_COL2");
					this.OnROLE_COL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_COL3", DbType="NVarChar(50)")]
		public string ROLE_COL3
		{
			get
			{
				return this._ROLE_COL3;
			}
			set
			{
				if ((this._ROLE_COL3 != value))
				{
					this.OnROLE_COL3Changing(value);
					this.SendPropertyChanging();
					this._ROLE_COL3 = value;
					this.SendPropertyChanged("ROLE_COL3");
					this.OnROLE_COL3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_USER_ROLES")]
	public partial class M_USER_ROLES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _URID;
		
		private string _USERID;
		
		private string _ROLE_CODE;
		
		private System.Nullable<System.DateTime> _UR_CREATE_DATE;
		
		private string _UR_CREATEUSER;
		
		private System.Nullable<System.DateTime> _UR_LASTUPDATE;
		
		private string _UR_LASTUPDATEUSER;
		
		private string _UR_COL1;
		
		private string _UR_COL2;
		
		private string _UR_COL3;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnURIDChanging(long value);
    partial void OnURIDChanged();
    partial void OnUSERIDChanging(string value);
    partial void OnUSERIDChanged();
    partial void OnROLE_CODEChanging(string value);
    partial void OnROLE_CODEChanged();
    partial void OnUR_CREATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUR_CREATE_DATEChanged();
    partial void OnUR_CREATEUSERChanging(string value);
    partial void OnUR_CREATEUSERChanged();
    partial void OnUR_LASTUPDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUR_LASTUPDATEChanged();
    partial void OnUR_LASTUPDATEUSERChanging(string value);
    partial void OnUR_LASTUPDATEUSERChanged();
    partial void OnUR_COL1Changing(string value);
    partial void OnUR_COL1Changed();
    partial void OnUR_COL2Changing(string value);
    partial void OnUR_COL2Changed();
    partial void OnUR_COL3Changing(string value);
    partial void OnUR_COL3Changed();
    #endregion
		
		public M_USER_ROLES()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long URID
		{
			get
			{
				return this._URID;
			}
			set
			{
				if ((this._URID != value))
				{
					this.OnURIDChanging(value);
					this.SendPropertyChanging();
					this._URID = value;
					this.SendPropertyChanged("URID");
					this.OnURIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this.OnUSERIDChanging(value);
					this.SendPropertyChanging();
					this._USERID = value;
					this.SendPropertyChanged("USERID");
					this.OnUSERIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ROLE_CODE
		{
			get
			{
				return this._ROLE_CODE;
			}
			set
			{
				if ((this._ROLE_CODE != value))
				{
					this.OnROLE_CODEChanging(value);
					this.SendPropertyChanging();
					this._ROLE_CODE = value;
					this.SendPropertyChanged("ROLE_CODE");
					this.OnROLE_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UR_CREATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UR_CREATE_DATE
		{
			get
			{
				return this._UR_CREATE_DATE;
			}
			set
			{
				if ((this._UR_CREATE_DATE != value))
				{
					this.OnUR_CREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._UR_CREATE_DATE = value;
					this.SendPropertyChanged("UR_CREATE_DATE");
					this.OnUR_CREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UR_CREATEUSER", DbType="NVarChar(50)")]
		public string UR_CREATEUSER
		{
			get
			{
				return this._UR_CREATEUSER;
			}
			set
			{
				if ((this._UR_CREATEUSER != value))
				{
					this.OnUR_CREATEUSERChanging(value);
					this.SendPropertyChanging();
					this._UR_CREATEUSER = value;
					this.SendPropertyChanged("UR_CREATEUSER");
					this.OnUR_CREATEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UR_LASTUPDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UR_LASTUPDATE
		{
			get
			{
				return this._UR_LASTUPDATE;
			}
			set
			{
				if ((this._UR_LASTUPDATE != value))
				{
					this.OnUR_LASTUPDATEChanging(value);
					this.SendPropertyChanging();
					this._UR_LASTUPDATE = value;
					this.SendPropertyChanged("UR_LASTUPDATE");
					this.OnUR_LASTUPDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UR_LASTUPDATEUSER", DbType="NVarChar(50)")]
		public string UR_LASTUPDATEUSER
		{
			get
			{
				return this._UR_LASTUPDATEUSER;
			}
			set
			{
				if ((this._UR_LASTUPDATEUSER != value))
				{
					this.OnUR_LASTUPDATEUSERChanging(value);
					this.SendPropertyChanging();
					this._UR_LASTUPDATEUSER = value;
					this.SendPropertyChanged("UR_LASTUPDATEUSER");
					this.OnUR_LASTUPDATEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UR_COL1", DbType="NVarChar(50)")]
		public string UR_COL1
		{
			get
			{
				return this._UR_COL1;
			}
			set
			{
				if ((this._UR_COL1 != value))
				{
					this.OnUR_COL1Changing(value);
					this.SendPropertyChanging();
					this._UR_COL1 = value;
					this.SendPropertyChanged("UR_COL1");
					this.OnUR_COL1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UR_COL2", DbType="NVarChar(50)")]
		public string UR_COL2
		{
			get
			{
				return this._UR_COL2;
			}
			set
			{
				if ((this._UR_COL2 != value))
				{
					this.OnUR_COL2Changing(value);
					this.SendPropertyChanging();
					this._UR_COL2 = value;
					this.SendPropertyChanged("UR_COL2");
					this.OnUR_COL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UR_COL3", DbType="NVarChar(50)")]
		public string UR_COL3
		{
			get
			{
				return this._UR_COL3;
			}
			set
			{
				if ((this._UR_COL3 != value))
				{
					this.OnUR_COL3Changing(value);
					this.SendPropertyChanging();
					this._UR_COL3 = value;
					this.SendPropertyChanged("UR_COL3");
					this.OnUR_COL3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_SYS_INFO")]
	public partial class M_SYS_INFO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SYS_ID;
		
		private string _SYS_VSERION;
		
		private string _SYS_UPDATE_CONTENT;
		
		private System.Nullable<System.DateTime> _SYS_UPDATE_TIME;
		
		private string _CODEID_FOR_SYSTYPE;
		
		private System.Nullable<System.DateTime> _SYS_CREATEDATE;
		
		private string _SYS_CREATEUSER;
		
		private System.Nullable<System.DateTime> _SYS_LASTUPDATE;
		
		private string _SYS_LASTUPDATEUSER;
		
		private string _SYS_COL1;
		
		private string _SYS_COL2;
		
		private string _SYS_COL3;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSYS_IDChanging(long value);
    partial void OnSYS_IDChanged();
    partial void OnSYS_VSERIONChanging(string value);
    partial void OnSYS_VSERIONChanged();
    partial void OnSYS_UPDATE_CONTENTChanging(string value);
    partial void OnSYS_UPDATE_CONTENTChanged();
    partial void OnSYS_UPDATE_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnSYS_UPDATE_TIMEChanged();
    partial void OnCODEID_FOR_SYSTYPEChanging(string value);
    partial void OnCODEID_FOR_SYSTYPEChanged();
    partial void OnSYS_CREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSYS_CREATEDATEChanged();
    partial void OnSYS_CREATEUSERChanging(string value);
    partial void OnSYS_CREATEUSERChanged();
    partial void OnSYS_LASTUPDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSYS_LASTUPDATEChanged();
    partial void OnSYS_LASTUPDATEUSERChanging(string value);
    partial void OnSYS_LASTUPDATEUSERChanged();
    partial void OnSYS_COL1Changing(string value);
    partial void OnSYS_COL1Changed();
    partial void OnSYS_COL2Changing(string value);
    partial void OnSYS_COL2Changed();
    partial void OnSYS_COL3Changing(string value);
    partial void OnSYS_COL3Changed();
    #endregion
		
		public M_SYS_INFO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYS_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long SYS_ID
		{
			get
			{
				return this._SYS_ID;
			}
			set
			{
				if ((this._SYS_ID != value))
				{
					this.OnSYS_IDChanging(value);
					this.SendPropertyChanging();
					this._SYS_ID = value;
					this.SendPropertyChanged("SYS_ID");
					this.OnSYS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYS_VSERION", DbType="NVarChar(50)")]
		public string SYS_VSERION
		{
			get
			{
				return this._SYS_VSERION;
			}
			set
			{
				if ((this._SYS_VSERION != value))
				{
					this.OnSYS_VSERIONChanging(value);
					this.SendPropertyChanging();
					this._SYS_VSERION = value;
					this.SendPropertyChanged("SYS_VSERION");
					this.OnSYS_VSERIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYS_UPDATE_CONTENT", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string SYS_UPDATE_CONTENT
		{
			get
			{
				return this._SYS_UPDATE_CONTENT;
			}
			set
			{
				if ((this._SYS_UPDATE_CONTENT != value))
				{
					this.OnSYS_UPDATE_CONTENTChanging(value);
					this.SendPropertyChanging();
					this._SYS_UPDATE_CONTENT = value;
					this.SendPropertyChanged("SYS_UPDATE_CONTENT");
					this.OnSYS_UPDATE_CONTENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYS_UPDATE_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> SYS_UPDATE_TIME
		{
			get
			{
				return this._SYS_UPDATE_TIME;
			}
			set
			{
				if ((this._SYS_UPDATE_TIME != value))
				{
					this.OnSYS_UPDATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._SYS_UPDATE_TIME = value;
					this.SendPropertyChanged("SYS_UPDATE_TIME");
					this.OnSYS_UPDATE_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODEID_FOR_SYSTYPE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CODEID_FOR_SYSTYPE
		{
			get
			{
				return this._CODEID_FOR_SYSTYPE;
			}
			set
			{
				if ((this._CODEID_FOR_SYSTYPE != value))
				{
					this.OnCODEID_FOR_SYSTYPEChanging(value);
					this.SendPropertyChanging();
					this._CODEID_FOR_SYSTYPE = value;
					this.SendPropertyChanged("CODEID_FOR_SYSTYPE");
					this.OnCODEID_FOR_SYSTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYS_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SYS_CREATEDATE
		{
			get
			{
				return this._SYS_CREATEDATE;
			}
			set
			{
				if ((this._SYS_CREATEDATE != value))
				{
					this.OnSYS_CREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._SYS_CREATEDATE = value;
					this.SendPropertyChanged("SYS_CREATEDATE");
					this.OnSYS_CREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYS_CREATEUSER", DbType="NVarChar(50)")]
		public string SYS_CREATEUSER
		{
			get
			{
				return this._SYS_CREATEUSER;
			}
			set
			{
				if ((this._SYS_CREATEUSER != value))
				{
					this.OnSYS_CREATEUSERChanging(value);
					this.SendPropertyChanging();
					this._SYS_CREATEUSER = value;
					this.SendPropertyChanged("SYS_CREATEUSER");
					this.OnSYS_CREATEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYS_LASTUPDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SYS_LASTUPDATE
		{
			get
			{
				return this._SYS_LASTUPDATE;
			}
			set
			{
				if ((this._SYS_LASTUPDATE != value))
				{
					this.OnSYS_LASTUPDATEChanging(value);
					this.SendPropertyChanging();
					this._SYS_LASTUPDATE = value;
					this.SendPropertyChanged("SYS_LASTUPDATE");
					this.OnSYS_LASTUPDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYS_LASTUPDATEUSER", DbType="NVarChar(50)")]
		public string SYS_LASTUPDATEUSER
		{
			get
			{
				return this._SYS_LASTUPDATEUSER;
			}
			set
			{
				if ((this._SYS_LASTUPDATEUSER != value))
				{
					this.OnSYS_LASTUPDATEUSERChanging(value);
					this.SendPropertyChanging();
					this._SYS_LASTUPDATEUSER = value;
					this.SendPropertyChanged("SYS_LASTUPDATEUSER");
					this.OnSYS_LASTUPDATEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYS_COL1", DbType="NVarChar(50)")]
		public string SYS_COL1
		{
			get
			{
				return this._SYS_COL1;
			}
			set
			{
				if ((this._SYS_COL1 != value))
				{
					this.OnSYS_COL1Changing(value);
					this.SendPropertyChanging();
					this._SYS_COL1 = value;
					this.SendPropertyChanged("SYS_COL1");
					this.OnSYS_COL1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYS_COL2", DbType="NVarChar(50)")]
		public string SYS_COL2
		{
			get
			{
				return this._SYS_COL2;
			}
			set
			{
				if ((this._SYS_COL2 != value))
				{
					this.OnSYS_COL2Changing(value);
					this.SendPropertyChanging();
					this._SYS_COL2 = value;
					this.SendPropertyChanged("SYS_COL2");
					this.OnSYS_COL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYS_COL3", DbType="NVarChar(50)")]
		public string SYS_COL3
		{
			get
			{
				return this._SYS_COL3;
			}
			set
			{
				if ((this._SYS_COL3 != value))
				{
					this.OnSYS_COL3Changing(value);
					this.SendPropertyChanging();
					this._SYS_COL3 = value;
					this.SendPropertyChanged("SYS_COL3");
					this.OnSYS_COL3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
